### ISSUE TITLE
Binding properties in deployer incorrect?

### ISSUE THREAD

**Issue by frosenberg** [spring-cloud/spring-cloud-dataflow#109]
I'm writing a deployer for kubernetes (will file a separate issue for that as I'm planning to contribute it - if desired).

As part of this. I'm a bit confused with the deployment parameters of the modules. When I run the following test: 
```
dataflow:>stream create --name deployment1 --definition "http --server.port=9999 | log" --deploy
```

I get the following parameters  when a module is deployed which I'm passing on to the `module-launcher`.

For the log module (I already converted them to uppercase, as I'm trying to pass them in as env vars):
```
MODULES=org.springframework.cloud.stream.module:log-sink:jar:1.0.0.BUILD-SNAPSHOT
SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION=deployment1.0
```

For the http module:
```
SERVER_PORT=9999
SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION=deployment1.0
MODULES=org.springframework.cloud.stream.module:http-source:jar:1.0.0.BUILD-SNAPSHOT
```

When I check my deployment, the messages are not send from `http` to `sink`. Upon reading up on the docs in spring-cloud-stream project, I figured out the the properties should be `SPRING_CLOUD_STREAM_BINDINGS_INPUT` and `SPRING_CLOUD_STREAM_BINDINGS_OUTPUT` (without the `DESTINATION`).  

Is this a bug or am I doing something wrong in my deployer implementation? The fix is very simple, I just had to change the `INPUT_BINDING_KEY` and `OUTPUT_BINDING_KEY` constants in the `org.springframework.cloud.dataflow.core.BindingConstants`. I can submit a PR once confirmed.

**Comment by mbogoevici** [comment]
Hi Florian,

Thanks for the interest and definitely contribute a PR for it, please :).

`SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION` is definitely correct, the documentation in Spring Cloud Stream is out of date (in other words `SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION` and `SPRING_CLOUD_STREAM_BINDINGS_OUTPUT` should have equivalent behaviour, `SPRING_CLOUD_STREAM_BINDINGS_OUTPUT` is essentially shorthand for `SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION`). 

We've had issues with passing environment variables in the past, especially when they are bound to a map, so I think this is an issue with Spring Cloud Stream. What is your target environment - do you mind sharing your deployer code, to try to reproduce this?

Thank you, 
Marius

**Comment by markfisher** [comment]
Just to provide a bit more context that might be helpful as you implement a deployer...

"spring.cloud.stream.bindings" is the key for a Map-typed property of all bindings on a module (e.g. "input" and "output" are keys in that map) defined here:

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/ChannelBindingServiceProperties.java

Each value in that Map is an instance of `BindingProperties`, of which "destination" is one of the properties:

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingProperties.java

However, if the only thing being bound is the destination property, we support a shortcut such that a `String` can be used in place of the `BindingProperties` instance, and that shortcut is made possible by this converter being registered:

https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/config/BindingPropertiesConverter.java

As Marius mentioned above, please do share some code, so we can reproduce it.

Regards,
Mark

**Comment by mbogoevici** [comment]
I think I've been able to reproduce this. Environment variables are mapped by the relaxed binder to `OUTPUT_DESTINATION` instead of `OUTPUT`, with the observed consequences. On the long run, this needs to be addressed in Spring Boot, but I think that for now we can work around it for this particular case.

**Comment by frosenberg** [comment]
Thanks for the quick help. I have a quick fix in my code right now to avoid the problem (i.e., mapping `OUTPUT_DESTINATION` to `OUTPUT` before passing it to Kubernetes). 

I'll prepare the deployer and push it to my forked repo over the weekend. We can then see if there is a better way to do this. I'll keep you updated.

**Comment by ericbottard** [comment]
Hi again Florian,

there is indeed an issue with binding properties to a Map when those are delimited with an underscore.
Is process environment the only way to propagate information to your module in kubernetes?
Could you use "regular" program arguments instead?
i.e. instead of 
```
SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION=deployment1.0
```
as an environment variable, could you spawn the module launcher with
```
java [....] --spring.cloud.stream.bindings.output.destination=deployment1.0
```

Environment variables often accept dots in them, **if they're not manipulated by a shell**. Could it be the case in kubernetes?

**Comment by frosenberg** [comment]
Thanks @ericbottard.

I could use regular parameters as well in Kubernetes, however I don't know how to pass them in so they work ;). It seems like the program arguments are not being passed to the module code itself, rather to the module-launcher. 

Do you think the arguments like this will work should work? 
```
java -jar target/spring-cloud-stream-module-launcher-1.0.0.BUILD-SNAPSHOT.jar --modules=org.springframework.cloud.stream.module:http-source:1.0.0.BUILD-SNAPSHOT --spring.cloud.stream.bindings.output.destination=ticktock --server.port=9999
```
What I observe is that the correct module is started but all arguments to the module are ignored? (like the `server.port` in this case).


Essentially, Kubernetes underneath starts a docker container. The docker container I use as a basis including samples how to run it are from this project: https://github.com/spring-cloud/spring-cloud-stream/tree/master/spring-cloud-stream-module-launcher. 

Kubernetes does not accept "." in the environment variables, this is why I transform them myself right now.

**Comment by ericbottard** [comment]
Yes, you need to qualify them by some prefix, so that the launcher knows that they are for that module (the launcher is able to launch several modules in a single process).
There is a helper method for that though, so that you don't have to do this yourself: https://github.com/spring-cloud/spring-cloud-dataflow/blob/392bc95f4791ce4234e1228f98ce98f043fbbd6d/spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-spi/src/main/java/org/springframework/cloud/dataflow/module/deployer/ModuleArgumentQualifier.java

You'd typically pass module parameters as well as deployment properties through this. Have a look [at this](https://github.com/spring-cloud/spring-cloud-dataflow/blob/392bc95f4791ce4234e1228f98ce98f043fbbd6d/spring-cloud-dataflow-module-deployers/spring-cloud-dataflow-module-deployer-cloudfoundry/src/main/java/org/springframework/cloud/dataflow/module/deployer/cloudfoundry/ApplicationModuleDeployer.java#L245-L247) for example

**Comment by frosenberg** [comment]
Ahh, thanks again @ericbottard 

Now I start to understand this qualifier thing :). It seems to append something like `args.0` or something. I'll give it a try and let you know.

**Comment by frosenberg** [comment]
@ericbottard the issue with passing it in as arguments and qualifying them with the `ModuleArguementQualifier` works fine. Closing the issue. 

I presume the environment variable issue will be resolved somewhere else.
