### ISSUE TITLE
Step Execution Count incorrect when same job is executed multiple times

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#1241]
When executing a batch job (with same job name) multiple times the step execution count for   for all instances are the same.  i.e. if a job has 3 steps, the step execution count for the first run will be 3.  The next time its run the step count for the current run and previous run will be 6.

Steps to reproduce.  Execute a batch job(task) and then rerun it.  Then go to the shell and execute a job execution list.

**Comment by cppwfs** [comment]
The issue is the StepExecution collection returned as a part of the JobExecution returns a list of all stepExecutions that were associated with the JobInstance.  The list of step executions that are returned will have null Id's except for those stepExecutions that are a part of the jobExecution.  Those stepExecutions that are a part of the jobExecution will have Id's.

**Comment by cppwfs** [comment]
Started to work on a solution, but looks like there is either a deeper issue or I missed something.  https://github.com/cppwfs/spring-cloud-dataflow/tree/SCDF-1241
Thoughts?

**Comment by ilayaperumalg** [comment]
@cppwfs I couldn't re-produce this issue as I see the expected behaviour. When I debug, I see the `step executions` are correctly set for the **given** job execution [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java#L95). 

The suggested fix above points to the `Shell` command `JobCommands` but I don't think we need to fix the issue at the shell as if it is really an issue then the fix requires to be in the `Controller` side of it so that all the REST clients wouldn't see it.

Could you confirm if you still see the issue?

**Comment by cppwfs** [comment]
Hey @ilayaperumalg Let me clarify a little bit.  
When viewing the Job Executions via the UI or via the shell it shows a `Step Executions Count`.
So when I create a composed task and launch it, for example :
```
task create foo --definition "AAA && BBB"
task launch foo
```
The `Step Executions Count` is 2.
However when I launch `foo` again, for example:
```
task launch foo --arguments "a=1"
```
The `Step Executions Count` for both job executions will be 4.
Hope that clarifies it a bit.

**Comment by ilayaperumalg** [comment]
@cppwfs yeah, this (it happens only for **composed** tasks) definitely clarifies things. I could
