### ISSUE TITLE
Make metrics properties key configurable

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#1298]
`StreamDeploymentController` forces adding `spring.cloud.stream.metrics.properties=spring*` for all apps.

As a user I'd like this to be configurable so that if in my app I want to expose something else than `spring*` keys, I could do it.

Also need to think how to tell user that keys prefixed with `spring` are needed for metrics to work.

**Comment by markpollack** [comment]
By default, the subset of metrics that is configured should be
`SPRING_CLOUD_STREAM_METRICS_PROPERTIES=spring.application.*,spring.cloud.application.*,spring.cloud.dataflow.*`

We do need to document that this can be set via 

1) Deployment property approach `app.*.spring.cloud.stream.metrics.properties`.  Since `extractAppProperties`
2) For all streams when staring SCDF  `spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.metrics.properties`
3) In stream definition via `--spring.cloud.stream.metrics.properties`

Using approach 1) and 2) is much more common.

I think we can just do a check for the existence of the key `spring.cloud.stream.metrics.properties` where we currently add them to `appDeployTimeProperties`.  Will need to test an verify.

**Comment by markpollack** [comment]
I noticed that we will also need to suppress `spring.application.json`, since that could expose sensitive creds.  So we can't do the wildcard `spring.application.*` but need to specify `spring.application.name` and `spring.application.index` explicitly.

**Comment by markpollack** [comment]
I guess we can check if the key `spring.cloud.stream.metrics.properties` is set in `CommonApplicationProperties`.  If it isn't we add the values above, if not we pass through what the use set.

**Comment by markpollack** [comment]
I believe we should also make `spring.metric.export.includes` configurable.  Since we only need the integration values of rates, if we set this to `integration**` by default, we would reduce the payload size.  By default we get everything under `/metrics` if this property is not set.
