### ISSUE TITLE
'Random Parameter' needed to execute Batch Jobs and Composed Tasks

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-dataflow#1489]
If I define a task that is a batch job and attempt to run it more than once, the second time it will fail with an exception:
```
org.springframework.batch.core.repository.JobInstanceAlreadyCompleteException: A job instance already exists and is complete for parameters={-spring.cloud.task.executionid=108}.  If you want to run this job again, change the parameters.
```

This is due the way spring batch requires different parameters every time a job is run, up to now we have been passing in a 'random' or current timestamp parameter each time to get around this, but I think this should be supported directly in Spring Cloud Dataflow eg by marking a task as re-runnable.  

Spring XD automatically passed a 'random' parameter to jobs presumably for this reason. 

However this seems to be more of an issue with the new composed tasks functionality in SCDF 1.2.0

For example (using the provided timestamp task) if I create a simple task definition

```
task create test-timestamp --definition "timestamp --format=\"yyyy\""
task launch test-timestamp
```

I can launch the task repeatedly without a problem, but if I create a composed task:

```
task create test-compose-timestamp --definition "timestamp1: timestamp --format=\"yyyy\" && timestamp2: timestamp --format=\"dd-MM-yyyy\""
task launch test-compose-timestamp
```

This will only run once, the second time I get the JobInstanceAlreadyCompleteException exception, due to the fact that composed tasks are implemented by a batch job.

To get this to work again I need to pass a new argument eg 

```
task launch test-compose-timestamp --arguments "random=abcd"
```

Presumably this 'feature' of spring batch should not be leaking into the composed task functionality.

A worse problem is that if my composed task is composed of batch jobs the arguments to the overall task do not seem to get passed into each sub task (job). So if I try to run a composed task of batch jobs it will trigger the first job but then that will fail with JobInstanceAlreadyCompleteException (assuming the job has run at least once) and there is no way to work around this as random or timestamp parameters are not passed into the sub job, so currently it seems its not possible to use composed tasks with jobs.

**Comment by cppwfs** [comment]
I disagree with the view that batch overflowed into the concept of composed tasks.  In this case it is rather composed tasks needs to have the ability to restart a failed composed task execution from the point of failure.  While we did discuss the re-running of composed tasks multiple times it was deemed at that time that each execution should be made unique by identifying parameters.   
We could discuss adding a parameter to the launch command in order to add an identifying parameter for each composed task execution.   Thus would the user to re-execute a task multiple times without them specifying a identifying parameter.

To the second point, I'll have to investigate further.  The composed-task-runner offers the feature to separate out properties and pass them to each task within the composed task run.

**Comment by mminella** [comment]
Spring Cloud Data Flow exposes Spring Batch as batch is intended to work.  Spring XD introduced a "random parameter" which was a mistake and has been addressed in Spring Cloud Data Flow.

Spring Batch provides the ability to configure a `JobParametersIncrementer` that handles this use case automatically.  If you are writing your own job, this should be used and Spring Boot will use it to generate a unique parameter each time the job is run.  

However, we do feel that you may be right in that the composed task runner should have that capability at least configurable.  We're going to move this issue over to the [composed-task-runner](https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/9) project for discussion.
