### ISSUE TITLE
Study design choices to support on-the-fly function composition

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1584]
As a developer, I'd like to add the ability to compose/chain functions into a single unit of work at runtime.

**Notes:**
- This feature allows the contribution model for arbitrary functions and orchestrating them as a chain of operations (similar to `aggregate apps` in SCSt).
- The idea is that functions can be chained as a composite unit and ran within a single SCSt application (1 JVM).
- There will be no messaging middleware/bindings necessary for function chaining. The communication is within the same thread/jvm.

**Acceptance:** 
- The design considers different chaining combinations _(e.g., source + processor, processor + processor(s), processor + sink, or source + processor + sink)_
- Consider the DB schema to support a new identifier to distinguish between a function-chain vs. regular apps in a stream
- Document API changes
- Document DSL proposals
- Document goals and anti-goals (gets into the following questions - define the supported specs)

**Questions:**
- Can you compose an entire stream made of functions? 
- What happens when we scale the app? 
- How's partitioning handled? 
- How can Flo adapt to this workload?
- How's TAP'ing handled?

**Comment by markfisher** [comment]
first take at some of the questions...

> Can you compose an entire stream made of functions?

I think that would end up being just an App (for unbounded `Supplier`) or Task (for bounded `Supplier`). The latter could even be used for things like `jdbc | process | store` when the JDBC source is only invoked intermittently anyways.

> How's partitioning handled?

Partitioning at the edges would be the same as normal, but since there are no physical topics for intermediate pipes, there would be no partitioning at those. If partitioning is needed at a certain boundary, that would be a pipe to opt-out of chaining.

> How's TAP'ing handled?

Similar to partitioning, with no physical channel, there is no point to tap. If TAP'ing is needed at a certain boundary, that would be a pipe to opt-out of chaining.

**Comment by olegz** [comment]
It appears that we differentiate between _function_ and conventional SCSt _app_ and I wonder why? Function simply exposes _functional_ programming model to a piece of functionality. Such functionality can have it's own class path and other dependencies and therefore developed/deployed as an independent module. In such case functional composition would be similar to the on/off discussions we're having on merging/aggregating two independent apps together to avoid queueing (if that is something one wants). In other words it would be somewhat complex without something clever, since we would have to deal with dependency merging which would not always be possible and/or clean.

So one way to look at composition question in the described scenario is to say that if functions come from different "modules", then they are not composable.
Am I missing something?

**Comment by sabbyanandan** [comment]
The foundation of this is available through SCSt's native integration with SCFn on the 2.1 release-train. From SCDF perspective, one can compose functions in the DSL via the `--spring.cloud.stream.function.definition=` property available to each SCSt (2.1) application. 

Here's an example:

> stream create foo --definition "http --server.port=9001 --spring.cloud.stream.function.definition=upper --spring.cloud.stream.bindings.output.contentType=text/plain | log" --deploy

Here: `upper` is a reusable function that's available to `http` in its classpath. Each payload arriving on port `9001` will be converted to uppercase, and sent over to the downstream consumer i.e. `log` sink. 

More details in the blog [here](https://spring.io/blog/2018/10/30/spring-cloud-stream-fishtown-rc1-2-1-0-rc1-release-announcement).
