### ISSUE TITLE
Task Launch Failed

### ISSUE THREAD

**Issue by larrying** [spring-cloud/spring-cloud-dataflow#1665]
when i executed "task launch --name myjob --arguments "--server.port=52416" " using Spring Shell, it failded, error is below:

> Binding to target org.springwork.boot.autoconfigure.web.ServerProperties@401e7803 failed:
> Property:server.port
> value:40491,52416
> Reason:Failed to convert property value of type 'java.lang.String to required type 'java.lang.Integer' for proerty 'port'

it seems to create a port 40491 automatically,then append to my port 52416
how to resolve?

**Comment by cppwfs** [comment]
Currently this is a bug in the Spring Cloud Deployer Local.   The local deployer adds a server.port (using a unused port)  to the arguments, if the server.port is not specified in properties. This prevents the tasks from using the default 8080 port and thus failing.   However it does not check to see if the server.port is set in the command line arguments.   I've opened a issue https://github.com/spring-cloud/spring-cloud-deployer-local/issues/77 on the Spring Cloud Deployer Local project to resolve this issue.   In the meantime you can move the server.port to the properties instead of the command line args and that should get you around this issue.

**Comment by cppwfs** [comment]
We can close this issue and use the https://github.com/spring-cloud/spring-cloud-deployer-local/issues/77 for future comments.

**Comment by larrying** [comment]
hi，when i launched the task that contained Spring Batch job, it started automatically with --server.port arguments.so,when i restarted the failed job,it is also with --server.port argumengs.

**Comment by cppwfs** [comment]
Are you using Spring Cloud Data Flow Local?

**Comment by larrying** [comment]
yes,i am using Spring Cloud Data Flow Local

**Comment by cppwfs** [comment]
I think we have gone full circle on this issue.  The problem you are facing is a bug https://github.com/spring-cloud/spring-cloud-deployer-local/issues/77 in the spring-cloud-deployer-local that is used by Spring Cloud Data Flow local.  In that it is injecting a server.port command line argument  if does not see a server.port specified in the properties (it should also check the args, which is the bug fix).  Until that fix is in place you can only set server.port via the --properties option when launching a task.  
Also this job is not going to be able to be restarted because of the bug.  The best bet is to remember to use properties for future executions until the bug is fixed.

**Comment by sabbyanandan** [comment]
We will address this in spring-cloud/spring-cloud-deployer-local#77.
