### ISSUE TITLE
Add versioning support for app registry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1736]
As a user, I'd like to register multiple versions of the app, so I can pick and choose what goes as the default.

**Design notes:**

1) Include a new boolean column (`useInDSL?`; values = Y or N) in the app-registry table.

2) Allow registration of "n" number of versions for the same app with same 'GAV' coordinates.

_examples:_
```
app register --name log --uri <PATH-TO-File>/log:1.1.0
app register --name log --uri <PATH-TO-File>/log:1.2.0
app register --name log --uri <PATH-TO-File>/log:1.2.1
app register --name log --uri <PATH-TO-File>/log:1.3.0
app register --name log --uri <PATH-TO-File>/log:1.4.0
```

3) Upon usage of a specific version in the DSL, we will update the `useInDSL` column for that record to "Y".

4) We will add a new command to change the default version.

> app default sink:log --version 1.4.0

5) The `app unregister` command can accept a `--version` property. If a version is unregistered, we could choose the next default.

6) The `app info` command will _require_ the version to be supplied (should also enable suggestion for all the registered versions)

7) Stream create workflow will use the version that is set to the default.
> stream create foo --definition "time | log" <- it could default to 1.4.0 for example

8) Stream update workflow only accepts a registered app version.
```
stream skipper update foo --properties version.log=1.2.0,app.log.logging.level=DEBUG <- this will work
stream skipper update foo --properties version.log=1.7.0,app.log.logging.level=DEBUG <- this will fail with validation error
```

**Comment by tzolov** [comment]
FYI, currently the app. `version` is squashed inside the  app `URI`.  In order to support multiple app version we need to:
* make the `version` a top level attributes in the `AppRegistration` (used in the comparison logic as well)
* To extend all relevant `AppRegistry` and `UriRegistry` method signatures that currently use `name` and `type` only.
* The most appropriate place to extract the app version form the uri is in the `AppRegistryController`
