### ISSUE TITLE
Manage Spring Batch jobs without task

### ISSUE THREAD

**Issue by wmz7year** [spring-cloud/spring-cloud-dataflow#1874]
Hello, I'm trying use spring cloud data flow embedded dashboard ui manage Spring Batch Jobs.
but job executions must have taskId. 

Is there any way to manage only Spring Batch jobs?

**Comment by sabbyanandan** [comment]
Hi, @wmz7year: To orchestrate Spring Batch Jobs in SCDF, they _must_ be ported to a Spring Cloud Task model. This is by design. There aren't any plans to diverge from this thinking.

Please refer to the Spring Batch Admin to SCDF [migration-guide](https://github.com/spring-projects/spring-batch-admin/blob/master/MIGRATION.md#migrating-from-spring-batch-admin-to-spring-cloud-data-flow) for more details.
