### ISSUE TITLE
Only set indexed property when deploying a partitioned stream

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#1876]
By setting this even for regular stream deployments, as a side effect, we are spawning StatefulSet pods in K8S, which is unnecessary. The requirement is to make sure it is applied only when a partitioned streaming characteristics are implied.

**Comment by mv78** [comment]
Additionally, this deployer property can not be overwritten. If we pass deployer.app-name.indexed=false or deployer.*.indexed=false. It only gets applied to source and not sink in the same stream.

**Comment by markpollack** [comment]
Thanks @mv78.  Don't you think it could lead to some confusion if this was allowed to be overridden?  If the stream was deployed using the deployment properties for partitioning (which should be what drives the use of indexes) and also the indexed property is overwritten, then one can end up with a stream that doesn't work as expected.

**Comment by mv78** [comment]
I am not sure I follow yoir logic. The indexed property grts set regardless
if stream is partitioned or not. I deployed simple stream time | log and it
created statefulset for log. I can not overwrite it to turn off statefulset.

**Comment by markpollack** [comment]
Yes, sorry, sort of two issues going on at once.  The purpose of this issue was to set the index property only when the stream is partitioned.  I am not sure why we coded it up the way it is now, I am in the middle of trying to sort that out.

Assuming that is in place, I think allowing to override the index property will open up conflicts when partitioning is being used.

**Comment by mv78** [comment]
That would be a problem only if someone choose to overwrite it? Otherwise
it would still vehave the same and default to indexed unless det to false
by deployer overwrite. Its a prpblem since stateful set gets created with
zero sized PVC which is meaningless in firstplace and is a deployment
problem in aws ebs based pvc as they can not be zero sized. So we need a
way to turn off indexed for non indexed streams.
