### ISSUE TITLE
Ensure that 1.2 deployed streams show 'empty value' for deployment properties in 1.3

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1912]
this is non-skipper mode

**Comment by ilayaperumalg** [comment]
@markpollack This is already taken care [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/af4344bc7a5bd5a78bb1596c279e53f985d4905a/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/AppDeployerStreamDeployer.java#L266). Did you still see this issue? or, this issue was created to capture this use case?

**Comment by sabbyanandan** [comment]
Is it safe to close this now?

**Comment by sabbyanandan** [comment]
Test#1:
1) Started SCDF and Shell's 1.2.3 release on MySQL
2) Deployed the following streams
> 1) stream create foo --definition "time | log" --deploy
> 2) stream deploy foo --properties "deployer.log.count=2"
3) Verified the test results 

Test#2:
1) Started SCDF and Shell's 1.3 BS release on MySQL (same DB from Test#1)
1.1) I had to re-register all the apps (since versioning is applied only in skipper-mode)
2) Deployed the following streams
> 1) stream create foo --definition "time | log" --deploy
> 2) stream deploy foo --properties "deployer.log.count=2"
3) Though the deployment failed in Skipper (see: spring-cloud/spring-cloud-skipper#464), the SCDF operations worked as expected
