### ISSUE TITLE
Add `named channel list` shell command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#197]
As a user, I'd like to have `named channel list` as shell command, so I can list all the available named-channels that I can directly interact with.

**Acceptance:**
Issuing: `dataflow:>named channel list` lists all the available named channels

**Comment by markfisher** [comment]
This one might need to be re-thought based on changes we are planning to make (e.g. no more prefixes for channels and no more separate concept of "tap"). For one thing we should not use the term "named channels" since the only difference for pipes within streams is that the names are generated based on a convention. Also, we probably want to call these "destinations", given that we are using that as the key in the binding properties. However, now that we are moving toward multiple binders, I'm not so sure it's feasible to list every possible destination across all of the possible binders that might be in use for a given dataflow system cc @mbogoevici

**Comment by mbogoevici** [comment]
I don't think we can list every possible destination either. One way in which this could work would be to list named destinations that have been part of a defined (or deployed?) stream, but that would require the admin server to retain even more state, which is not very desirable IMO. Also, it would be hard to see how this would work with dynamic routing.
