### ISSUE TITLE
Investigate execution of AboutControllerTests.SkipperMode

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2022]
The test does not appear to be executed when running the build via Maven, but does execute when run in Intellij

**Comment by ilayaperumalg** [comment]
It is because we have [this](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/pom.xml#L184) filtering of test classes with the Suffix `Tests` and `Test` only to be included in maven surefire plugin report generation.

Along with the test class `SkipperMode`, the other test class `ChecksumNoDefault` is also excluded now :-)
