### ISSUE TITLE
Unable to register an app using docker URI in 1.3.1 SCDF

### ISSUE THREAD

**Issue by bondalapati98** [spring-cloud/spring-cloud-dataflow#2065]
Recently we have upgraded scdf to 1.3.1 and while using spring-cloud-dataflow-shell-1.3.1.RELEASE.jar to register an app using the below url, getting an error. This worked spring-cloud-dataflow-shell-1.3.0.M1.jar.

Shell start command:
-----------------------
java -jar spring-cloud-dataflow-shell-1.3.1.RELEASE.jar --dataflow.mode=skipper  --dataflow.uri=http://128.100.4.91:31659

Register Command
----------------------
app register --name retaildatasource --type source --uri docker://192.168.2.221:8500/skillnet.retaildatasource:420

Error:
------
dataflow:>app register --name retaildatasource --type source --uri docker://192.168.2.221:8500/skillnet.retaildatasource:419
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Invalid docker resource URI: docker:192.168.2.221:8500/skillnet.retaildatasource:419 

Please let us know if we are missing anything with this new verion.

Thank you very much.

**Comment by sabbyanandan** [comment]
Hi, @bondalapati98. To keep track of apps and the associated versions in SCDF (via Skipper) for downstream lifecycle-management, we expect Maven and Docker URIs conform to best practices. It used to be open-ended in previous GA releases, with no validation in fact. 

For Docker specifically, the recommended path format, for example, is `docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE`; where `springcloudstream` is the repository, `log-sink-rabbit` is the image-name, and `1.3.1.RELEASE` is the image-tag. You can read more about it in the [reference-guide](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.1.RELEASE/reference/htmlsingle/#_register_a_versioned_stream_app).

Which server implementation are you using?  As far as the Docker daemon is accessible by SCDF, you don't have to specify "host:port". You can simply point to the repository, image-name, and the version to resolve it locally (e.g., `docker://springcloudstream/log-sink-rabbit:1.3.1.RELEASE`). That's how we resolve OOTB apps in [Kubernetes-server](https://docs.spring.io/spring-cloud-dataflow-server-kubernetes/docs/1.3.1.RELEASE/reference/htmlsingle/#getting-started-deploying-streams).

**Comment by bondalapati98** [comment]
@sabbyanandan Thanks for your reply. We are using Nexux repository and I think there is no option to specify the URL without port. This has been working since 1.3.0 release and suddenly stopped working from 1.3.1

**Comment by sabbyanandan** [comment]
It would have worked in 1.3 M1 (per your previous comment); however, since the first-1.3-milestone, we have evolved wrt Skipper integration significantly, and this validation is a _requirement_ in the system. It'd prevent bogus entries and fail-fast instead of failing at runtime. 

If you're already using Nexus (I haven't seen it used for Docker Registry), you may consider switching to Maven artifacts instead. The host, port, and artifactory credentials can be supplied to the server as [configuration properties](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.1.RELEASE/reference/htmlsingle/#configuration-maven). 

All this said, I'm not sure what else we can do here. The system expects the Docker artifacts to be of a particular format for several downstream benefits including app-versioning, canary deployments, and as well for consistency in application-registry.

**Comment by bondalapati98** [comment]
Thanks @sabbyanandan  We will try with your recommendations.
