### ISSUE TITLE
Enhance SCDF to dynamically change scale of subscribers and consumers at runtime

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-dataflow#2157]
Currently, SCDF receives metrics from all apps via metrics service.
It would be good addition to have SCDF to dynamically scale up consumers to increase message processing throughput based on message rate of the queue/exchange its bound to or using consumer utilization rate for given queue.

I am thinking that spring cloud starter could provide mechanism for deployed consumers to receive its queue consumer rate and expose it as custom metrics. Than when k8s deployment is created, we can also add horizontal pod autoscaler spec to tie to that custom metrics so that consumer app would be autoscaled based on consumer rate for their respective queue.

Any thoughts? Is this more suited for Spring Cloud Stream project?

**Comment by sabbyanandan** [comment]
This is not in the scope of SCDF itself, but rather, we delegate it to the platform where SCDF is deploying the Apps to. For instance, in PCF, you'd be able to scale the applications at runtime using the [Autoscaler](https://docs.pivotal.io/pivotalcf/2-3/appsman-services/autoscaler/using-autoscaler.html), which can be configured to scale apps +/- depending on a variety of metrics including queue-depth. Likewise, the other platforms will have a similar support that you could leverage.

Alternatively, you could use the SCDF+Skipper APIs to invoke a stream-update operation to increment the count of a particular app in the streaming data pipeline. 

Since we delegate and depend on the platform's value-adds, we don't have plans to build an embedded component to do that.
