### ISSUE TITLE
Document prerequisites to perform parallel execution of Tasks in a Composed Task graph

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2279]
As a user, I'd like to orchestrate a Composed Task graph to run "n" number of Tasks in parallel. For that, I'd like to refer to the documentation on the prerequisites and recommend practices.

**Acceptance:**
- Be more explicit about all the available CTR properties/docs under "Configuring the Composed Task Runner". Link to the CTR repo doesn't say much
- Explain `split-thread-core-pool-size` under "Launching a Composed Task" section with an example

**Comment by mminella** [comment]
Do we want to change the default for this?  While 1 may be a "sensible default" when running a batch job and using threads for the execution model, that's not what is actually happening in this case.  Since we're delegating to a cloud runtime for this, maybe something like 4 is a more "sensible default"...

**Comment by sabbyanandan** [comment]
Sure, that sounds reasonable. See: spring-cloud-task-app-starters/composed-task-runner#40.

**Comment by cppwfs** [comment]
We had a discussion at inception of CTR because, I had defaulted it to 5 (IIRC) when we working on the initial release.  It was decided to stay at 1 because :
1) it was a sensible default.
2) It prevents users from reporting the issue as a scaling problem, i.e. "I ran 5 and now it fails for some odd reason".
