### ISSUE TITLE
Task Definition status returns `unknown` in 1.6.0.M2 Version

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2327]
I have found this bug in SCDF 1.5.2.
This bug been resolved in 1.6.0m1. If you look on main task screen it is really now displayed in the right way:
![image](https://user-images.githubusercontent.com/15521647/42876626-eed05b22-8a8f-11e8-8d48-8a3325774ca3.png)
But if you go down at task summary page, it looks like:
![image](https://user-images.githubusercontent.com/15521647/42876674-1083f648-8a90-11e8-9144-53671ae889c1.png)
REST response for "/tasks" has wrong status too. For example:
http://Localhost:9393/tasks/definitions/SequentialScheme_for_2018-07-14_date-viewing-maker_14
![image](https://user-images.githubusercontent.com/15521647/42876787-736ed0d4-8a90-11e8-8e95-8aee69bfb03c.png)
REST response for "/jobs" looks better:
![image](https://user-images.githubusercontent.com/15521647/42877176-77e056e6-8a91-11e8-8de4-30881207023a.png)
But if i need to get task status of definite operation. I have to go to main task endpoint, look for job id, go to job endpoint, find right step and get right status.

Could you fix it? 

P.S.  If i got it wrong, describe where please.

**Comment by Rostish** [comment]
I have found right endpoint http://10.101.53.100:9393/tasks/executions/{id} where is right status.
But for what other status is used to?

**Comment by sabbyanandan** [comment]
Hi, @Rostish. Thanks for the report. What you're seeing is a bug indeed - we will address it in 1.6 GA release. Also, this appears to be a problem specifically in the Task Summary page in the UI since the REST response includes the correct status in `taskExecutionStatus` field. The same also looks good on the jobs response.

I will move it to the UI repo.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#866

**Comment by sabbyanandan** [comment]
It turns out the issue is actually with the "Task definition" endpoint. It was intentionally kept not to rely on the newly added `taskExecutionStatus` field for backward compatibility reasons. We would have to replicate whatever we do on the "Task list" endpoint to display the correct status on the summary page.
