### ISSUE TITLE
Restarting a failed batch job

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2450]
Out of a task having multiple batch jobs, if one job fails and I try to restart it then only that job should restart. Currently, all jobs run again and the ones which were successful end up failing due to the command line error.

**Comment by sabbyanandan** [comment]
Hi, @siddhantsorann. When reporting issues, it'd be good if you can share more details about the problem. Perhaps also a reproducible (Task w/ multiple batch-jobs) sample if possible. 

Please have a look at the [wiki](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) for more details.

**Comment by siddhantsorann** [comment]
hey, I just basically wanted to know that when I restart a batch job because it failed will it always run all the jobs in the task again?  or is there a way or can a feature be implemented which will only run the failed batch job again?

**Comment by cppwfs** [comment]
Well it depends on how you implement your job.   But out of the box, if you try to restart a job that has already completed successfully, it will throw an exception stating that the job has already completed.

**Comment by sabbyanandan** [comment]
@siddhantsorann: +1 to Glenn's response. If you have a custom batch-job and if you're handling the restartability flow, yes, you'd be able to restart from where it got cut off. Here's a [Spring Batch example](https://docs.spring.io/spring-batch/4.0.x/reference/html/index-single.html#customReadersWriters) that describes the restartability semantics of a sample `ItemReader` and `ItemWriter`. 

In fact, SCDF's composed-task-runner is a batch-job, so that helps us to better handle the [lifecycle](http://docs.spring.io/spring-cloud-dataflow/docs/1.6.3.RELEASE/reference/htmlsingle/#_the_lifecycle_of_a_composed_task) of individual steps in the composed-task [graph](http://docs.spring.io/spring-cloud-dataflow/docs/1.6.3.RELEASE/reference/htmlsingle/#_composed_tasks_dsl). 

All that said, please use StackOverflow or Gitter for questions going forward.
