### ISSUE TITLE
Dockerizing spring boot app error while executing task

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#2481]
I have taken the batch-job task which runs 2 simple batch jobs from the samples given by scdf. I dockerized it using the following dockerfile. 
Dockerfile:
```
FROM java:8
WORKDIR /
ADD target/batch-job-2.0.1.BUILD-SNAPSHOT.jar batch-job-2.0.1.BUILD-SNAPSHOT.jar
CMD java -jar batch-job-2.0.1.BUILD-SNAPSHOT.jar
```
I pushed this to my docker hub. In my scdf server I add an app with: 
```
dataflow:>app register --name test1 --type task --uri docker:siddhantsorann/batch-job:latest
Successfully registered application 'task:test1'
```
And then I execute it. On executing nothing happens, logs are also empty and it just adds it to the execution list with no start or end time. In the server logs i get: 
`2018-10-09 12:18:47.408  INFO 6241 --- [nio-9393-exec-4] o.s.c.d.spi.local.LocalTaskLauncher      : Command to be executed: docker run -e SPRING_APPLICATION_JSON={"endpoints.jmx.unique-names":"true","endpoints.shutdown.enabled":"true","spring.datasource.username":"root","spring.datasource.url":"jdbc:mysql://localhost:3306/scdf","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","server.port":"28405","spring.cloud.task.name":"test1","spring.datasource.password":"root","spring.jmx.default-domain":"test1-c3c87d4b-672b-4f1b-90f7-c3811b82d33d"} -p 28405:28405 siddhantsorann/batch-job:latest --spring.cloud.task.executionid=1`

Now when i execute only the docker run command on my local to test it, i get an error: 
```
siddhant@Blr-Siddhant:~$ docker run -e SPRING_APPLICATION_JSON={"endpoints.jmx.unique-names":"true","endpoints.shutdown.enabled":"true","spring.datasource.username":"root","spring.datasource.url":"jdbc:mysql://localhost:3306/scdf","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","server.port":"28405","spring.cloud.task.name":"test1","spring.datasource.password":"root","spring.jmx.default-domain":"test1-c3c87d4b-672b-4f1b-90f7-c3811b82d33d"} -p 28405:28405 siddhantsorann/batch-job:latest
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

**Comment by sabbyanandan** [comment]
Hi, @siddhantsorann. We discussed this in other issues recently. When reporting bugs, please be as specific as possible. It'd help if you can actually also include a repeatable sample. The description needs version information for us to be able to reason through what could be wrong - see [README](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues) for guidelines.

In this case, though, you cannot make the batch-job run standalone. Until it runs locally, it _cannot_ run when orchestrated via SCDF, so please check your App and the Dockerfile. If you need a sample, please have a look at this [repo](https://github.com/sabbyanandan/partitions/tree/master/fruitsource). 

I will close this since it doesn't relate to SCDF directly.
