### ISSUE TITLE
Performance issue: job page with lots of executions is slow

### ISSUE THREAD

**Issue by nWidart** [spring-cloud/spring-cloud-dataflow#2583]
Hello,

**Description:**
On the Jobs page I have 657 executions. The request to get the executions from aws takes 38 seconds to load. 

The endpoint is `/jobs/executions?page=0&size=30`, but it doesn't look like it's paginating due to the slowness.

**Release versions:**
This is using `1.7.0.RELEASE`.

**Steps to reproduce:**
Let a stream run with a time source for a while, in order to have a lot of executions.

**Screenshots:**
![image](https://user-images.githubusercontent.com/882397/48695166-b2cf5780-ebde-11e8-83e9-a1eba9a0d808.png)

Thank you,

**Comment by sabbyanandan** [comment]
Hi, @nWidart. Thank you for the report. What database are you using? Also, where is SCDF running? _(laptop?)_ More details about the environment setup would help to replicate and troubleshoot it on our side.

**Comment by nWidart** [comment]
The database is mariadb and scdf is running in aws.

Our kubernetes cluster contains:

- 3 masters c4.large
- 6 workers m5.large

Thanks,

**Comment by nWidart** [comment]
Hello,

It sounds similar indeed.By now I have `2065` jobs in that list. The API endpoint took 18 seconds.
![image](https://user-images.githubusercontent.com/882397/49209779-af488700-f3bb-11e8-86f3-655aae34432c.png)

And in the dashboard:
![image](https://user-images.githubusercontent.com/882397/49209822-d30bcd00-f3bb-11e8-91f5-dec5c4764abb.png)

I'm not sure what the difference can be. It also contains spring batch applications with 4-5 steps each, but I assume the content of the batch job isn't related to the load time on the index page.

Also note that the task > execution page loads fast with `2067 task executions`.

**Comment by cppwfs** [comment]
I took another stab at it with a fresh repository.  This time Launching 1000 batch jobs each job having 5 steps each (instead of the 1)  The goal would be see if there was any kind of impact on the time in which we get the results.   And based on the results below, there was no real impact.   
```
real	0m0.144s
user	0m0.006s
sys	0m0.006s
```
Also I'm curious, in your last update you stated it took 18 seconds to get the result while previously it took 38 seconds with fewer entries..

**Comment by nWidart** [comment]
the 18 seconds is in postman.

In my previous post I also show a screenshot of 39 seconds in chrome network tab.

**Comment by cppwfs** [comment]
I was able to reproduce.   Long story short.  My original tests with 5 Steps per Batch Job did not show the error.  However 500 steps per Batch Job does reproduce the issue quickly.  
The issue is that the query returns back all the steps for each batch job.   Now the question is this expected behavior for users (ie. to get all batch job data for this restful call)?   i.e. it has been here since the 1.0 days.     What are your thoughts @sabbyanandan ?
