### ISSUE TITLE
Parsing error when deploying a stream with SpEL expression

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2587]
As a user, while deploying the following streams in v1.7 BS, I observe the attached error. 

_(notice that the `''` is not preserved at the time of deployment)_

```
dataflow:>stream create timer --definition "time --date-format=hhmmss | log"
Created new stream 'timer'

dataflow:>stream create minutes --definition ":timer.time > transform --expression='payload.substring(2,4)' | log"
Created new stream 'minutes'

dataflow:>stream deploy --name timer --properties deployer.*.bootMajorVersion=2
Deployment request has been sent for stream 'timer'

dataflow:>stream deploy --name minutes --properties deployer.*.bootMajorVersion=2
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 115E:(pos 140): unexpected data in stream definition ')'
:timer.time > transform --spring.cloud.stream.bindings.applicationMetrics.destination=metrics --transformer.expression=payload.substring(2,4) | log --spring.cloud.stream.bindings.applicationMetrics.destination=metrics
```

I also see the same error while creating the stream without `''`.

```
dataflow:>stream create minutes --definition ":timer.time > transform --expression=payload.substring(2,4) | log"
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 115E:(pos 58): unexpected data in stream definition ')'
:timer.time > transform --expression=payload.substring(2,4) | log
                                                          ^
```

**Comment by sabbyanandan** [comment]
When this occurs, I see the following in the Dashboard. 

![image](https://user-images.githubusercontent.com/1562654/48755899-e2687900-ec4b-11e8-8e9b-637cf8114707.png)

**Comment by tzolov** [comment]
@sabbyanandan , what apps version are you testing with? Darwin? 
Wonder if `--expression='payload.substring(2,4)'` shouldn't be --expression='new 
 String(payload).substring(2,4)'` instead?

**Comment by sabbyanandan** [comment]
It doesn't matter; same error on both Celsius and Darwin. I believe there are issues with parsing and how we persist.

**Comment by sabbyanandan** [comment]
@aclement: Do you have any ideas?

**Comment by aclement** [comment]
will have a look

**Comment by aclement** [comment]
I suspect we got away with this kind of thing before because comma wasn't a special character that meant we could parse `--expression='payload.substring(2,4)'` or `--expression=payload.substring(2,4)` (so with or without quotes) just fine.  But since comma is now special due to unbound apps, you can't blindly lose the quotes.  Still digging.

**Comment by aclement** [comment]
Ok, it is kind of what I thought but not as simple to fix as I'd hoped. It does seem to be skipper specific too. When the parser parses that DSL it will create an `ArgumentNode` with a name of `expression` and value of `payload.substring(2,4)`.  At this point the fact that there were quotes in the original has been completely discarded.  It looks like skipper persists this:
```
...
   "transformer.expression": "payload.substring(2,4)"
...
```

The problem will happen if you try to 'reconstruct' a DSL definition from this because the quotes are missing.  Two options:
- persist the quotes all the way through (but then everywhere we currently deal with values will have to unwrap them). This may cause issues with the quoting in the skipper manifest yml things too.
- when re-creating the DSL skipper will have to be aware of the quoting rules and apply quoting for them.

The quoting rules are probably (going from memory!):
- if your argument value has a space in it, you need quotes around the whole thing.
- if your argument has a comma in it, you need quotes around the whole thing. (possibly same for arguments with other special chars in, like `|` or `>` - would need to check that)
- if you have quotes around it (single quotes) then any single quotes within it need to be doubled up so that they are recognized as not terminating the quoted string (e.g.  `'#jsonThing(''foo'',2)'` - see the double single quotes around foo to act as escaping).

If you follow those rules you should be able to build a valid stream definition that will parse.  I'm a bit nervous because it may not be identical to the original stream (you are trying to conjure up quotes where you think they had them in the original stream) but it should be a close approximation that'll work. I do have a branch that preserves quotes (Well, getValue() doesn't include them but toString() does - so you don't need to change lots of existing code happy with getValue() you just need to recognize you should use toString() if you want the value 'as possibly quoted in the DSL' - but that feels like it'll get messy for you in the JSON).

**Comment by markpollack** [comment]
We had quite the bad experience trying to preserve quotes in YAML, we would have to do a more major rewrite to use YAML liberal String support but I recall that also had some issue at the time we were experimenting with all this.  We should revisit for skipper 2.0, so option / hack #2 seems like what we should try now...

I can't follow in the discussion when the parse issue occurs, only in the reconstruction of the expression?  I though that code was only executed on stream list.

Can you point us to the branch you mention?

**Comment by markpollack** [comment]
We had quite the bad experience trying to preserve quotes in YAML, we would have to do a more major rewrite to use YAML liberal String support but I recall that also had some issue at the time we were experimenting with all this.  We should revisit for skipper 2.0, so option / hack #2 seems like what we should try now...

I can't follow in the discussion when the parse issue occurs, only in the reconstruction of the expression?  I though that code was only executed on stream list.

Can you point us to the branch you mention?

**Comment by aclement** [comment]
Here is the commit that I was thinking about: https://github.com/aclement/spring-cloud-dataflow/commit/7c13f4c52b90850e0ff1b048fee94b9ecd2e1507

Fundamentally we currently discard quotes that were used after parsing and just capture the value of the argument. But with that commit above we remember which quotes were used (if any) and you can access the actual value with getValue() or a quoted form of the value via toString().  But it was just a work in progress as I was experimenting.

hack #2 is probably the right route, even moreso if you may also be adding other properties into the DSL you are re-constructing because you'll need to do the same handling for those (do they have a space in, or a comma in, if so then quote them...).

**Comment by markpollack** [comment]
After reading that blog post to refresh myself on all the string options in YAML, adding a single quote will screw up expressions/values that have `\t` and such.  The syntax

```
bash: |
  #!/usr/bin/env bash
  echo "Help, I'm trapped in a YAML document!"
  exit 1
```
seems like what may solve the problem on the skipper side, but I remember playing with this and we backed out, but can't remember why.  We would have to save every application/deployment property in that style.

**Comment by markpollack** [comment]
See https://github.com/spring-cloud/spring-cloud-dataflow/pull/2608 that includes Andy's branch and a small fix to improve the reversal of the DSL for simple cases involving comma in expressions.
