### ISSUE TITLE
Upgrade to Boot 2.1.x

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#2606]
As a developer, I'd like to upgrade 2.x/master to Boot 2.1.x. This is a prerequisite to security rewrite [spring-cloud/spring-cloud-dataflow#2579].

Child of #914.

**Comment by sabbyanandan** [comment]
Also address: "DO NOT depend on Spring Cloud BOM"

**Comment by markpollack** [comment]
The issue depending on spring cloud bom was that we wanted to upgrade the boot version, but had to wait for a spring cloud build release.  If there is a way to update the version of boot w/o waiting for a new build of spring cloud build, that would address the concern. @olegz  ?

**Comment by olegz** [comment]
So, basically we've created a new module to provide boot version directly for us. Basically look at the commit history [here](https://github.com/spring-cloud/spring-cloud-stream-starters/commits/master). Pay attention to [this commit](https://github.com/spring-cloud/spring-cloud-stream-starters/commit/e2ec84af784fc5120f222f8b2f38250dd42c4d47) and subsequent polishing commits after that. Prior to this commit this module (spring-cloud-starter-parent) did not exist. 
So that is the trick. Let me know if you need more details.

**Comment by sabbyanandan** [comment]
Thanks, @olegz! The commit clarifies everything - so cool. So, @jvalkeal, you're on the right track already. We will create our own "parent' BOM, and with that, we will have the flexibility to upgrade Boot whenever we want.

**Comment by sabbyanandan** [comment]
@jvalkeal: The parent-module scope is moved to spring-cloud/spring-cloud-dataflow#2648 (scheduled for 2.0 M2). We will _only_ address the Boot upgrade as part of this issue.
