### ISSUE TITLE
SCDF 2.x Custom deployed app never changes it's state to deployed

### ISSUE THREAD

**Issue by barisa** [spring-cloud/spring-cloud-dataflow#2652]
**Description:**
After deploying a custom Spring Boot - Spring Cloud Stream app, the state is still **"deploying"** even the app is running. I've created a sample project to demonstrate this behavior (see https://github.com/barisa/sample-scdf-datagenerator).

**Release versions:**
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server-local",
      "version": "2.0.0.BUILD-SNAPSHOT"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.0.0.BUILD-SNAPSHOT"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.0.0.BUILD-SNAPSHOT"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.0.0.BUILD-SNAPSHOT",
      "url": "https://repo.spring.io/libs-snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.0.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-2.0.0.BUILD-SNAPSHOT.jar"
    }
  },
  "featureInfo": {
    "analyticsEnabled": true,
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulerEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthorizationEnabled": false,
    "isFormLogin": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.1.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.0.BUILD-SNAPSHOT",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.0.4.RELEASE",
      "springVersion": "5.0.8.RELEASE"
    },
    "taskLauncher": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "1.3.9.RELEASE",
      "deployerName": "LocalTaskLauncher",
      "deployerSpiVersion": "1.3.4.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "Linux 4.9.125-linuxkit",
      "platformClientVersion": "4.9.125-linuxkit",
      "platformHostVersion": "4.9.125-linuxkit",
      "platformType": "Local",
      "springBootVersion": "2.0.4.RELEASE",
      "springVersion": "5.0.8.RELEASE"
    }
  }
}
```

**Steps to reproduce:**
see sample project https://github.com/barisa/sample-scdf-datagenerator

**Comment by sabbyanandan** [comment]
@barisa: Thanks for the steps included in the sample repo. Could you also describe how you're starting SCDF?

**Comment by tzolov** [comment]
Hi @barisa, 

Thanks for raising this issue! I've just opened a PR that should solve it: https://github.com/barisa/sample-scdf-datagenerator/pull/1/files

There are two important bits:

* You must add the `org.springframework.boot:spring-boot-starter-web` and `org.springframework.boot:spring-boot-starter-actuator` dependencies in order for SCDF to track the application's state via the `Health` and `Info` actuator endpoints. - Apparently we have a gap in our app documentation and we need to fix the http://start-scs.cfapps.io/ app generator. 

* I've removed custom `spring.cloud.stream.bindings.output.destination` channel name as SCDF by default presumes that the `output` name. For handling a custom and multiple channel names you can review the new SCDF Application DSL:  http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#spring-cloud-dataflow-stream-app-dsl

Finally the `Greenwich.RC1` has been released few days ago so use it instead of `Greenwich.M1`

Please let me know if this works for you?

**Comment by tzolov** [comment]
Related information https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#spring-cloud-stream-preface-actuator-web-dependencies
