### ISSUE TITLE
Create Helm chart for 2.0

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow#2689]
Do after RELEASE as image need to be published etc

- [x] Add support for Kafka
- [x] Update docs

**Comment by chrisjs** [comment]
we may also want to sync our in-tree sample files along with AT configurations as theres a bit out of sync between each. the generated helm chart templates seem to be the most robust with probes, mysql config for skipper, etc. 

whichever path is chosen, its probably best just to keep things consistent

**Comment by chrisjs** [comment]
getting started as configs should be stable and snapshot builds usable

**Comment by chrisjs** [comment]
done, changes stashed in branch until release ready

**Comment by vxavictor513** [comment]
@chrisjs Any chance to include Prometheus & Grafana into the chart?

**Comment by chrisjs** [comment]
@vxavictor513 not at this time. after this chart is released, if you would like, feel free to add support and make a PR.

**Comment by sabbyanandan** [comment]
@vxavictor513: One other thing. We will have to be mindful about the getting-started experience, because Prometheus + Grafana _require_ at least a 3G or more memory, so the K8s cluster should have the capacity to handle the load. Even if we add support for it in the future, we will have to build a toggling mechanism to signup for these components explicitly, as opposed to provisioning them by default. 

It will break the Minikube and Docker Engine based local getting-started experience otherwise. 

Anyway, something to think about - feel free to contribute the improvement in a separate PR.

**Comment by chrisjs** [comment]
yes; i should have been more clear about that - given these are optional components the PR would be expected to have functionality disabled by defualt and enabled via an explicit `set` param

**Comment by chrisjs** [comment]
PR submitted @ https://github.com/helm/charts/pull/12285

**Comment by chrisjs** [comment]
merged
