### ISSUE TITLE
Integration With AppDynamics

### ISSUE THREAD

**Issue by ptanwar27** [spring-cloud/spring-cloud-dataflow#2950]
**Problem description:**
we use appDynamics for enterprise monitoring, I want to know if there is a recommended way to get metrics from spring cloud data flow into appD except instrumenting    Java directly”.

**Solution description:**
Please provide integration with appDynamics to help monitor SCDF pipelines and without changing our enterprise monitoring tools.

**Description of alternatives:**

**Additional context:**

**Comment by sabbyanandan** [comment]
Hi, @ptanwar27. In SCDF v2.0, we switched the metrics/monitoring strategy to be based on Micrometer and its supported [monitoring systems](https://micrometer.io/docs). In this foundation, it is possible to monitor the streaming pipelines as a whole or at the individual application included in the data pipeline, too. See ["Stream Monitoring"](http://docs.spring.io/spring-cloud-dataflow/docs/2.0.0.RC1/reference/htmlsingle/#streams-monitoring) section to learn more about how this can be put together for Prometheus and InfluxDB. Likewise, it could be possible for other listed monitoring systems as well. 

As for AppDynamics, there's an open story in Micrometer [see: micrometer-metrics/micrometer#575]. It appears to include a lot of interesting details; perhaps you could chime in on the issue and share your use-cases to bring in the visibility to the community. Once when Micrometer supports it, you could build streaming apps with the relevant Micrometer dependencies in the classpath so that the channel-metrics can be collected and persisted to AppDynamics automatically.

**Comment by sabbyanandan** [comment]
Closing this since there's nothing directly we can in SCDF until Micrometer supports it.
