### ISSUE TITLE
Update Skipper deployment in K8s to include MySQL as the database

### ISSUE THREAD

**Issue by allanmoso** [spring-cloud/spring-cloud-dataflow#3006]
**Description:**
After deploying a stream, and skipper is restarted, the deployed stream applications are now orphaned from SCDF; they can no longer  be undeployed from SCDF.

**Release versions:**
Implementation Version: 2.0.0.RELEASE (spring-cloud-dataflow-server)
Core: 2.0.0.RELEASE (Spring Cloud Data Flow Core)
Dashboard: 2.0.0.RELEASE (Spring Cloud Dataflow UI)
Shell: 2.0.0.RELEASE (Spring Cloud Data Flow Shell)

**Additional context:**
Deployed in Kubernetes.

**Comment by sabbyanandan** [comment]
@allanmoso: Are SCDF/Skipper use a persistent database or are you relying on the default (H2)? _(H2 is in-memory database and it is not recommended for use in production)_

**Comment by allanmoso** [comment]
@sabbyanandan : The way we have it setup is pretty much this: https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/src/kubernetes

The SCDF server has a mysql datasource configured. (The skipper does not.)

**Comment by sabbyanandan** [comment]
Good point. I can't seem to remember why and how we didn't plug a persistent storage option for Skipper deployment. It should be and we can do that by default. 

However, this shouldn't stop you from doing it on your own. Unless you switch to a persistent storage option, upon Skipper crash/restarts, you will lose the deployment footprint persisted in the in-memory (H2) database.

Please update the Skipper deployment and point to persistent storage (e.g. MySQL) similar to how it is done in SCDF. If you're on v2.0, you would need a different database, because SCDF and Skipper rely on flyway migration scripts associated with each of server releases.

**Comment by allanmoso** [comment]
Thanks. I applied the changes in #3010 and verified that stream statuses survives Skipper restarts now.
