### ISSUE TITLE
When setting spring cloud data flow (scdf) 2.x as maven dependency (for running as "local") of a regular spring boot app, the dataflow local server is unable to start as its asking for "cloud foundry" properties to be set(even though trying to run only as local)

### ISSUE THREAD

**Issue by jobas2007** [spring-cloud/spring-cloud-dataflow#3116]

**Comment by sabbyanandan** [comment]
Hi, @jobas2007. It is unclear as to what you're trying to do. Could you elaborate by editing the description with more details? More specifically, if you could list all the steps in regards to how you're attempting to start SCDF locally, it'd help

**Comment by jobas2007** [comment]
Thanks for response Sabbyanandan... basically below are the steps

1) Created a simple spring boot app from spring initializer and imported in eclipse
2) Added dependency for scdf (spring cloud dataflow server) 2.0.1.RELEASE in project pom , along with other dependencies for Oracle jdbc etc
3) defined some properties for in application.properties file for oracle connectivity etc
4) Ran the application as Java app (using JDK 1.8)
NOTE: Doing this , so as to do lot of easy customization for project/organization needs to get deployed into available linux host etc

Getting below error in start up


****Application Failed to Start
Binding to taget org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.cloud.deployer.cloudfoundary' to org.springframework.cloud.deployer.spi.cloudfoundary.CloudFoundaryConnectionProperties failed:

Properties: spring.cloud.deployer.cloudfoundary.password
Value : null
Reason: must not be null

...............and similar for other properties

The question is , i am simply trying to use the SCDF as local server, why it is still asking for cloudfoundary ?

**Comment by sabbyanandan** [comment]
Thanks for the update!

We do not promote the model of wiring-in SCDF autoconfiguration through a new Spring Boot application. We used to provide support for it back in 2017, but we have moved away from that model (also: Initializr) due to a variety of issues and classloading complexities. 

Our recommended model for Local, CF, or K8s is to use the binary or the Docker image that we ship with every release. For customizations to SCDF such as adding the proprietary Oracle driver in the classpath, you'd have to clone and build the project locally. Unfortunately, at the moment, there's no other ideal approach.

If you continue to see issues with the local build, please add a comment and reopen it.
