### ISSUE TITLE
Cannot switch binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#312]
As a user, I'm trying to switch to `rabbit` from the default `redis` as the binder, but I'm unable to successfully bootstrap with the following include/exclude combination at stream deployment time.

**example:**
```
stream create tweets1 --definition "twitterstream | log"
stream deploy tweets1 --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.BUILD-SNAPSHOT,module.*.excludes=:*-redis"

stream create tweetlang2  --definition "tap:stream:tweets1 > log"
stream deploy tweetlang2 --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.BUILD-SNAPSHOT,module.*.excludes=:*-redis"
```

**error:**
```
2016-01-18 10:15:38.581 ERROR 72625 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.IllegalStateException: Cannot perform binding, no proper implementation found
```

**Comment by ericbottard** [comment]
The underlying issue seems to be NoClassDefFound on `AbstractBindingPropertiesAccessor`, which seems to come from the fact that the version of spring-cloud-stream that is brought in is M3. I haven't yet been able to diagnose the dependency path that leads to that, but this may help anyone wanting to tackle this

**Comment by ilayaperumalg** [comment]
I could switch the binder successfully via dataflow DSL.

@sabbyanandan This could be the typo in your DSL: `module.*.excludes=:*-redis`. Note the **:** character without wildcard prefix.

The DSL I used is:

```
stream deploy a1 --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.BUILD-SNAPSHOT,module.*.excludes=*:*-redis"
```

**Comment by sabbyanandan** [comment]
Strange. The following works (with the `:` and no `*` prefix) when it's wired to use the milestone instead of SNAPSHOT bits. 

```
stream deploy tweetlang --properties "module.*.includes=org.springframework.cloud:spring-cloud-stream-binder-rabbit:1.0.0.M3,module.*.excludes=:*-redis"
```

cc:/ @mbogoevici

**Comment by markpollack** [comment]
Assuming there isn't some regression here, this is an argument to have a binding applied to all the streams by default, as it is a common case, for any of our ootb modules, as an admin feature

**Comment by mbogoevici** [comment]
Hi,

Both `:` and `*:` will actually work, as empty space is treated as a wildcard. See http://download.eclipse.org/aether/aether-core/1.0.0/apidocs/org/eclipse/aether/util/filter/PatternExclusionsDependencyFilter.html for reference.

Regarding the issue itself, we should use binder versions that are compatible the `spring-cloud-stream` core version used by the module, although that can get fairly complicated on the long run (it's not always obvious, especially for custom modules). There is the option of potentially overriding spring-cloud-stream itself if necessary, although IMO we should avoid this kind of issue and try to keep the dependencies between binder implementations and SCS core to a minimal level. Lastly, however, instability due to the use of SNAPSHOT versions is a problem that's hard to avoid. 

@markpollack : can you explain your suggestion? All streams have a binding by default, which is what the modules are built with, i.e. Redis. It would make sense though (at least until we figure out an alternative to the module launcher) to have a way to override the bindings in a simpler fashion via admin server (and potentially ensuring that the binder version is the right one).

**Comment by ericbottard** [comment]
@sabbyanandan Can you make sure you're using the latest (SNAPSHOT) version for the modules you're trying to use? Already registered modules are not re-registered on startup, so you may be using an old version. Also, can you confirm the root cause is NoClassDefFound on `AbstractBindingPropertiesAccessor`

**Comment by markpollack** [comment]
What I mean is this.  I am in a company shop uses Kafka. I now have to May a 'deployment property tax' and tell every stream that uses out ootb modules over and over again to exclude redis, include Kafka, and know some ick aether sytnax as well as artifact names I don't care about.  Not exactly a friendly easy "time | log" experience.  Instead we should tell the admin at startup - you should favor always deploying Kafka for out ootb modules by adding the metadata.  That is one possible approach, I'm sure we can think of some others.

**Comment by markfisher** [comment]
I'd rather find a solution that has nothing to do with include/exclude functionality. The most obvious option would be to build and distribute each of our OOTB "module" JARs in multiple flavors, for each Binder (and/or possibly a JAR that includes all Binders, especially now that multi-binder configuration is supported even within the scope of a single `spring-cloud-stream` application). The choice of default Binder type at the Admin level could then drive the artifact registry configuration.

**Comment by trisberg** [comment]
We've been talking about doing away with the includes/excludes for some time, never seen a good suggestion for how to handle the interesting combination of a `jdbchdfs` task though. Should we have "flavors" for rabbit-mysql-hortonworks, kafka-mysql-hortonworks, rabbit-mysql-pivotalhd, kafka-mysql-pivotalhd, rabbit-postgres-hortonworks, ... and so on?

**Comment by markfisher** [comment]
Personally, I am increasingly less convinced that we should be doing "runtime assembly". I think at some point we just have to make it as easy as possible for users to build and register the combination they want to use. We could of course provide prebuilt artifacts for the most common combinations as we see fit.
