### ISSUE TITLE
Setting default contentType to JSON doesn't work

### ISSUE THREAD

**Issue by MarounMaroun** [spring-cloud/spring-cloud-dataflow#3143]
**Description:**

I have a simple RabbitMQ source and RabbitMQ sink.

When I send a message with a JSON payload, with `content_type -> application/json` in the properties, the sink receives the message with `contentType -> application/octet-stream`.

I need the `contentType` to be JSON, and not `octet-stream`.

In my docker-compse, I tried adding to the environment:

```
spring.cloud.dataflow.applicationProperties.stream.spring.default.contentType=application/json
```

(also at the application level)

but this didn't help.

**Release versions:**

```
spring-cloud-dataflow-server:2.0.1.RELEASE
spring-cloud-skipper-server:2.0.0.RELEASE
```

**Comment by sabbyanandan** [comment]
This is not an SCDF/Skipper question; it is more about the apps itself. Besides that, for questions like this, StackOverflow is recommended. Since you already have a [active discussion](https://stackoverflow.com/questions/55612650/cant-change-content-type-from-application-octet-stream-to-application-json-in-r?noredirect=1#comment97920175_55612650) in StackOverflow, I will close this to avoid duplicate efforts.
