### ISSUE TITLE
Add tag for springcloud/spring-cloud-dataflow-prometheus-local in dockerhub

### ISSUE THREAD

**Issue by dim777** [spring-cloud/spring-cloud-dataflow#3178]
At present moment there are only tags 2.1.0.BUILD-SNAPSHOT and 2.0.2.BUILD-SNAPSHOT available in docker hub https://hub.docker.com/r/springcloud/spring-cloud-dataflow-prometheus-local/tags for spring-cloud-dataflow-prometheus-local image.
But in docker-compose file defined version from env variable $DATAFLOW_VERSION
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/docker-compose.yml
And for example for 2.0.2.RELEASE there are no available docker image. Please fix docker tags for image spring-cloud-dataflow-prometheus-local

**Comment by sabbyanandan** [comment]
Hi, @dim777. There two different versions of  `docker-compose.yml` files; one for [`2.0.x`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/2.0.x/spring-cloud-dataflow-server/docker-compose.yml) and another for [`master`/`2.1.x`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server/docker-compose.yml). Specifically, the 2.1.x file has evolved and there's a different image in use in it (i.e., `springcloud/spring-cloud-dataflow-prometheus-local`). 

All the said, if you want to use `master`, you have to use `2.1.0.BUILD-SNAPSHOT` version since that is the baseline on this branch. If you want to use `2.0.2.RELEASE`, you _must_ also use 2.0.x [`docker-compose.yml`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/2.0.x/spring-cloud-dataflow-server/docker-compose.yml) since that points to the previous design, likewise a different app/image. 

In fact, the v2.0.2 getting-started steps in the reference guide point to the following file. 

>  wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.0.2.RELEASE/spring-cloud-dataflow-server/docker-compose.yml

I hope this clarifies.

**Comment by dim777** [comment]
Ok thx
