### ISSUE TITLE
Improve Composed Task DSL to support multiple transitions to converge at a common step

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3263]
As a user, I have a requirement to branch out to multiple transitions from a step, and also have all the transitions to run a common downstream step.

For example, 
I'd like to branch out from the `Import` step to form transitions like this:

![image](https://user-images.githubusercontent.com/1562654/58904960-82a05f80-86bd-11e9-8b1a-22d08172ff51.png)
----
I'd then want all these transitions to _still_ run a common step, which in this case is `Backwards`.

![image](https://user-images.githubusercontent.com/1562654/58904935-75837080-86bd-11e9-8103-5bf90f684f89.png)
----
Though it is possible to build that representation in the UI today, it results in bogus generated DSL. 

The workaround today is to add a no-op step in the DSL to make the transitions all run in as a composite unit, while the no-op runs in parallel.

![image](https://user-images.githubusercontent.com/1562654/58905210-13773b00-86be-11e9-8bc3-fe369ef12023.png)
----

Associated DSL:
```
<Import: timestamp 'ERROR'->t1: timestamp 'ERROR2'->t2: timestamp || t3: timestamp> && Backwards: timestamp
```

**Comment by aclement** [comment]
@cppwfs @mminella Any comments on the proposal here to allow just one thing in a split (allowing split to effectively be used to define a 'nested flow'), did I overlook something? Is it too dirty of a hack? (Doesn't feel toooooo bad). Reasoning below.

For reference, the SCDF docs on composed task: https://docs.spring.io/spring-cloud-dataflow/docs/1.2.0.RELEASE/reference/html/spring-cloud-dataflow-composed-tasks.html

The challenge here is because we want T1 and T2 (transition exits from the first task) to run something afterwards and not just end the composed task (by jumping to end)

We have the split construct `<…>`, it is currently used for running tasks in parallel, but interestingly it does encapsulate a ‘nested flow’ within the composed task. By that I mean all exits from the split run the next task in sequence (usually, see nuance below with failing tasks in a split), so for

`<aaa || bbb || ccc> && qux && quux`

`aaa`, `bbb`, or `ccc` will all run then `qux` then `quux` afterwards.

Furthermore:

`<aaa ‘*’-> ddd || bbb || ccc> && qux && quux`

`aaa`, `bbb`, `ccc`, `ddd` will all run then `qux` then `quux` afterwards.

At the moment we enforce that a split/nested-flow must have two tasks in parallel, so this is an error:

`<aaa> && qux && quux`

But what if it weren’t an error? If we treated that scenario simply as ‘one thing to run in parallel’ (kinda meaningless but simply the simplest case of ‘run all the different branches in the split at the same time’). Then we could address this bug and remove the need for `T3` in the graph, it would become this:

`<Import: timestamp 'ERROR'->t1: timestamp 'ERROR2'->t2: timestamp> && Backwards: timestamp`

Is this a cheat/hack? Doesn't feel too bad actually.

It would mean `aaa && bbb && ccc` is the same as `<aaa> && <bbb> && <ccc>`.  We would need to update the docs to say `<…>` defines a sub flow.

Glenn pointed me at:
https://github.com/spring-cloud-task-app-starters/composed-task-runner/blob/master/spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitorTests.java and after modifying the parser to allow `<...>` with just one thing inside I was able to write:

```
@Test
public void nestedFlow_ghSCDF3263() {
	setupContextForGraph("AAA && <failedStep 'FAILED' -> EEE 'FOO' -> CCC> && BBB");
	Collection<StepExecution> stepExecutions = getStepExecutions();
        Set<String> stepNames = getStepNames(stepExecutions);
        assertEquals(4, stepExecutions.size());
        List<StepExecution> sortedStepExecution = getSortedStepExecutions(stepExecutions);
        assertEquals("AAA_0", sortedStepExecution.get(0).getStepName());
        assertEquals("failedStep_0", sortedStepExecution.get(1).getStepName());
        assertEquals("EEE_0", sortedStepExecution.get(2).getStepName());
        assertEquals("BBB_0", sortedStepExecution.get(3).getStepName());
}
```
Without the use of `<...>` there the steps would be `AAA`, `failedStep`, `EEE` without `BBB`.

The only nuance is that if the task within the split exits via FAILED and that is not handled by transition then the whole composed task will exit.

So this:
`AAA && <failedStep 'FAILED' -> EEE 'FOO' -> CCC> && BBB` (assuming failedStep exits by FAILED)
will run `AAA`, `failedStep`, `EEE`, `BBB`
`AAA && <failedStep 'FOO' -> CCC> && BBB` (assuming failedStep exits by FAILED)
will run just `AAA` and `failedStep`.  BBB will not run even though outside the nested flow. 

If we go with this, we will need to:
- update the parser to allow single entries in `<...>`
- add tests for the new construct to SCDF and composed-task-runner (the one mentioned above)
- modify/verify the graph to text algorithm can this pattern.

**Comment by cppwfs** [comment]
To me it makes sense.  We will also want to update the documentation to discuss the nested flow.  And adjust the wording around the splits.   @mminella thoughts?

**Comment by sabbyanandan** [comment]
@aclement: It seems reasonable to accept `<...>` construct for single entries also. If treating this as a valid entry simplifies to even solve for the reported problem, let's do it.  And, it is not a breaking change in any capacity, so it is good from that angle as well. 

Once when we clarify the purpose of `<...>` with a few examples/tests, that should be sufficient to educate the users.
