### ISSUE TITLE
scdf k8s failed update stream by updating namespaces

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3331]
**Description:**
As a user, i am trying to deploy the same stream (time|log) using diferents namespaces.
I can 'see' that namespaces (k8s) are multiple running "environments play,work,live"

I can deploy stream using namespaces by examples "default". ok
It is start running ok.

Then, i want to deploy it into another namespace ... using "update stream".
Ok, let'g go, i change textfield about namespaces using another one.

I got the following error :
"Package to upgrade has no difference than existing deployement/deleted package. Not upgrading."

and web screen back to "gray" protection" needed f5-reload.

Can i deploy same stream using differents namespaces?

**Release versions:**
````
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.1.2.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.1.2.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.1.2.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.1.2.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.1.2.RELEASE/spring-cloud-dataflow-shell-2.1.2.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": true,
    "grafanaEnabled": true
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.0.2.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.0.3.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.1.3.RELEASE",
      "springVersion": "5.1.5.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      },
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.0.2.RELEASE",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.0.2.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformType": "Kubernetes",
        "springBootVersion": "2.1.3.RELEASE",
        "springVersion": "5.1.5.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "http://localhost:3000",
    "token": "",
    "refreshInterval": 15
  }
}
````

**Custom apps:**
It is a simple stream using defaults time | log

**Steps to reproduce:**
time | log

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

![imagen](https://user-images.githubusercontent.com/1777753/61046051-799d5f00-a3dc-11e9-9dac-afb410db6626.png)

**Additional context:**

**Comment by sabbyanandan** [comment]
Similar to the comment at https://github.com/spring-cloud/spring-cloud-dataflow/issues/3324#issuecomment-510479458, there's not much information here as to how you configured multi-platforms in SCDF + Skipper. Just because you have >1 namespaces in K8s, SCDF won't be able to support it for you automatically. You _must_ configure the list of namespaces as different platform accounts in SCDF (for tasks) and Skipper (for streams). 

If you do have >1 platforms configured in SCDF + Skipper, `stream platform-list` and `task platform-list` should list all the available options, so when you deploy streams or launch tasks, you can optionally also pass (eg: `--platformName=play`) as a property.

Recently, I shared a multi-platform configuration sample for Tasks and the steps with a user in Gitter (see [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5ca534393ebbdc55b3589964)). There's also a [test story](https://github.com/spring-cloud/spring-cloud-dataflow/issues/2852#issuecomment-462957754) with some samples. This is also described in the [ref. guide](https://docs.spring.io/spring-cloud-dataflow/docs/2.1.2.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-deploy-stream). 

I hope this helps.

Please post questions like this in StackOverflow going forward.
