### ISSUE TITLE
Admin local will not start if Kafka is already running locally

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-dataflow#334]
The default H2 port is 9092, same as the default port for Kafka brokers. Unless there is a very specific need to to use port 9092 for H2, I would suggest to customize that value for our embedded DB.

**Comment by ilayaperumalg** [comment]
Given the port value is read from the H2 datasource URL and we need to have generic properties for all the datasource values,  may be we can just keep a different port for now.

**Comment by trisberg** [comment]
We should change the default port in the TaskController in the admin-starter and any other admin SPI implementations as well.

**Comment by ilayaperumalg** [comment]
I believe this issue is addressed in this PR: https://github.com/spring-cloud/spring-cloud-dataflow/pull/338

I also noticed that the `TaskController` uses `@Value` annotated variables to resolve `spring.datasource.*` properties. I wonder if we can use `@Value` in Controller classes as they don't get resolved I guess.

**Comment by trisberg** [comment]
OK, created an issue for the YARN SPI - https://github.com/spring-cloud/spring-cloud-dataflow-admin-yarn/issues/56
