### ISSUE TITLE
spring-data-flow-server fails to initialize in minikube/helm

### ISSUE THREAD

**Issue by damaru-inc** [spring-cloud/spring-cloud-dataflow#3358]
**Description:**
I'm trying to run this with minikube and helm according to the instructions at

https://dataflow.spring.io/docs/installation/kubernetes/helm/

and the spring-release-dataflow-server process fails with the following exception. This happens on both Mac and Windows:
```
Caused by: java.lang.IllegalStateException: No valid primary TaskPlatform configured
	at org.springframework.cloud.dataflow.server.config.features.SchedulerConfiguration.primaryTaskPlatform(SchedulerConfiguration.java:110)
	at org.springframework.cloud.dataflow.server.config.features.SchedulerConfiguration.schedulerService(SchedulerConfiguration.java:77)
```

**Release versions:**
Kubernetes 1.15.0
Helm version 2.14.0
minikube version 1.2.0
Spring Cloud Data Flow Helm Chart 2.3.0 (I also tried 2.2.1 and hit the same issue.)

**Steps to reproduce:**
Follow the instructions at https://dataflow.spring.io/docs/installation/kubernetes/helm/

Run the helm install command with the options:
```
server.service.type=NodePort
rbac.create=false
```

**Comment by sabbyanandan** [comment]
Hi, @damaru-inc. Just so that I follow, I wanted to attempt it locally using the Helm Chart 2.3.0. Here are my findings:

**Minikube:**
```
➜ spring-cloud-dataflow ➤ ca5b1a41|master⚡
± minikube start --cpus=4 --memory=7596
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=4, Memory=7596MB, Disk=50000MB) ...
🐳  Configuring environment for Kubernetes v1.12.0 on Docker 18.09.6
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "sabby"
```

**Install SCDF Chart:**
```
± helm init

± helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Unable to get an update from the "spring-incubator" chart repository (http://spring-incubator.cfapps.io):
	Failed to fetch http://spring-incubator.cfapps.io/index.yaml : 404 Not Found
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.

± helm install --name my-release stable/spring-cloud-data-flow

± helm list
NAME      	REVISION	UPDATED                 	STATUS  	CHART                       	APP VERSION  	NAMESPACE
my-release	1       	Fri Jul 19 12:46:17 2019	DEPLOYED	spring-cloud-data-flow-2.3.0	2.1.2.RELEASE	default
```

**Schedule Task:**
```
± k get cronjobs
NAME     SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
crssss   */1 * * * *   False     0        42s             3m9s
```

With that, I was able to run the Task every minute successfully until I destroyed the definition. Likewise, a simple `time | log` stream runs just OK with RabbitMQ, too.

I'm on Mini 1.2.x and that defaults to K82 1.12, but the platform version shouldn't cause the bootstrap anomalies, though. 

If it is reproducible, perhaps you could share the entire logs/stacktraces from SCDF and Skipper.

**Comment by damaru-inc** [comment]
Thanks for the quick response! The only difference between what I ran and what you did was you used 4 cpus for minikube (I used 2), you used a 50GB disk (I used 40GB), and you used the name 'my-service'. I ran it the same way you did (but with a bit more RAM) and it worked. If those resource numbers made the difference, I would have hoped to see a different kind of error, but anyway it works for me now.

**Comment by sabbyanandan** [comment]
Interesting. The node(s) in K8s would have failed with resource constraint errors. 2 CPUs is small to run K8s, SCDF, Skipper, Rabbit, MySQL, and the stream/task applications. Perhaps the readiness/liveness probes from upstream components were failing due to the constrained environment, so that may have caused the downstream to choke. We will review the setup to see if there are opportunities for improvements.

**Comment by damaru-inc** [comment]
That sounds perfectly plausible. I saw in the server logs that it was trying to configure with H2, which I found odd, and now that makes sense if MySql wasn't up yet. I think all you need to do is recommend that people use a minimum of 4 CPUs. Thanks again for the very quick help.
