### ISSUE TITLE
Datasource properties transmission

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3371]
**Problem description:**
Right now, datasource properties are passed with spring main datasource properties :
spring.datasource.url
spring.datasource.username
spring.datasource.password
spring.datasource.driverClassName

This is great because tasks need to know the database infos to write their execution progress.

However, in the case of a microservice/multi service architecture, if we use a separate database or schema for scdf, and the tasks need to access another business databasse/schemas, we have an issue. 

It would be great if we could choose another prefix for database properties transmission.

**Solution description:**
I think that specifiying a prefix via spring dataflow configuration could be interesting:

ex: spring.cloud.dataflow.datasource-prefix=scdf

Then transmitted properties would become :
scdf.datasource.url
scdf.datasource.username
scdf.datasource.password
scdf.datasource.driverClassName

Task/Batch implementation is then straightforward thanks to @ConfigurationProperties("scdf.datasource") and DataSourceProperties mapping :

```java
@Configuration
@ConditionalOnProperty(value = "scdf.datasource.url")
public class ScdfDatasourceConfiguration {

  @Bean
  @Primary
  @ConfigurationProperties("spring.datasource")
  public DataSourceProperties firstDataSourceProperties() {
    return new DataSourceProperties();
  }

  @Bean
  @Primary
  @ConfigurationProperties(prefix = "spring.datasource.hikari")
  public HikariDataSource dataSource() {
    return firstDataSourceProperties().initializeDataSourceBuilder()
        .type(HikariDataSource.class)
        .build();
  }

  @Bean
  @ConfigurationProperties("scdf.datasource")
  public DataSourceProperties scdfDataSourceProperties() {
    return new DataSourceProperties();
  }

  @Bean
  public DataSource scdfDataSource() {
    return scdfDataSourceProperties().initializeDataSourceBuilder()
        .type(DriverManagerDataSource.class)
        .build();
  }

  @Bean
  public BatchConfigurer batchConfigurer() {
    return new DefaultBatchConfigurer(scdfDataSource());
  }

  @Bean
  public TaskConfigurer taskConfigurer() {
    return new DefaultTaskConfigurer(scdfDataSource());
  }
}

```

**Description of alternatives:**
I replaced TaskServiceUtils and modified updateTaskProperties method to use scdf prefix instead of spring one.

**Comment by sabbyanandan** [comment]
Hi, @Tetradeus. Thank you for reporting it. I believe this is somewhat related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/2048. 

We tend to inherit and default to what Boot provides as the set of properties/configs as much as possible; likewise, the datasource configurations follow the same paradigm, too. Introducing SCDF specific datasource properties might not be the right approach here, but we can investigate it in v2.3.

**Comment by Tetradeus** [comment]
Hi @sabbyanandan, thanks for your reply. It is not so related to #2048 because I am not talking about table prefix but datasource connection properties.

I think scdf datasource transmission is a good idea, I was just thinking of a way to make it more micro services oriented. It really matches our needs to have a different database/schema for task informations/centralization.

I think that the actual default behaviour is good for people using the same database/schema for everything (monolith behaviour). 

I see 2 ways to solve the issue of separating schema/database for task information and business process : either have a way to disable datasource properties transmission and let the user set it himself, or add the prefix properties solution I proposed (I also think that the prefix solution is interesting because it is simple to configure a datasource via this way).

I would be pleased if you could investigate this in v2.3.

Thanks a lot.

**Comment by markpollack** [comment]
There are two scenarios here, 1) using only tasks 2) using spring batch.  

In the spring batch case the standard practice has been that the database which does the accounting of steps/chunks etc is the same as the 'business' database.  This practice is in order to have transactional guarantees about the batch job accounting tables together with transactional guarantee of the business data. 

The task case is different in that often there is no need to have such guarantees of business data being in the same database as the task accounting table.  Hard to estimate but it seems often enough no business database is involved with a task.  That leaves the case you are talking about, in which case I do agree it seems unnatural for the 'task database' to take center stage by using 'spring.datasource.url', since all the real work in the task is being done in another database.  

If we could have done this from scratch, it may have worked out, but introducing this now would end up causing a great deal of confusion, because we would be supporting two modes of configuration (old and new) and products that install data flow, such as the PCF tile, would need to be updated, also I believe the composed task runner would need to be updated.  So while I understand your position, I don't think it would be a good idea to introduce this change, leaving 'one way to do it' is a better option even if it means that for your tasks the database configuration has to live in a 'second slot'.
