### ISSUE TITLE
Launching task by scheduler in k8s generates no external-execution-id 

### ISSUE THREAD

**Issue by rallepalle** [spring-cloud/spring-cloud-dataflow#3403]
**Description:**
Launching a task in dashboard manually an external execution id is generated and written into postgres table task_execution.
Launching the same task by scheduler no external execution id is created !
SCDF server running on k8s.

**Release versions:**
SCDF Server Release 2.2.0

**Screenshots:**
![Screenshot 2019-08-05 at 17 13 54](https://user-images.githubusercontent.com/5922404/62475242-f259c600-b7a4-11e9-9c02-e192dff77d99.png)

see postgres table task_execution:
![Screenshot 2019-08-05 at 17 35 48](https://user-images.githubusercontent.com/5922404/62477253-e2dc7c00-b7a8-11e9-9fbb-d9623a30618d.png)

**Comment by rallepalle** [comment]
![Screenshot 2019-08-05 at 17 32 41](https://user-images.githubusercontent.com/5922404/62476412-3cdc4200-b7a7-11e9-970c-5e14c378374a.png)

**Comment by cppwfs** [comment]
This is because SCDF applies an external-execution-id to the task execution record immediately after launching the task.  Since the task execution is handled by Kubernetes Cron Jobs it does not apply the external execution id.    We are looking at developing a Scheduled Task Launcher to resolve this as well as other issues not supported by various platform scheduling services.

**Comment by cppwfs** [comment]
Will be resolved when #3519 is merged.

**Comment by robinsomarajv** [comment]
How to instruct cloud task to use the task id generated by SCDF always?
