### ISSUE TITLE
Investigate and document the missing Helm Chart customizations

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3410]
As a developer, I'd like to study the possible customizations to the Helm chart from the provisioning standpoint, so we could prioritize and scope it for the incremental releases.

Notes:
- Folks are increasingly switching to Helm to provision SCDF and the related components. The HA capacity for message brokers, databases (MySQL vs. external), and the downstream stream/task deployment customizations are some of the commons touchpoints today. What other gaps exist? Can they be parameterized? If parameterizing all of it is complicated (too much code / technical debt), is there an alternative? 

- Look at other packaging options. Example: Duffle and Replicated.

**Comment by chrisjs** [comment]
reviewed with @markpollack today, walked through the following:

* Crossplane
* Duffle/CNAB
* Replicated Ship
* Replicated Vendor
* Kustomize & Helm

The proposed outcome is to use the Helm chart as the "source of truth" where ongoing improvements, enhancements, etc would be made and the current thinking would be to use the chart to auto-generate deployment files in a `kustomize` layout provided in the source tree as well as using these generated files in acceptance tests rather than the hardcoded yaml.

https://github.com/spring-cloud/spring-cloud-dataflow/issues/2778 for the most part speaks to this proposed outcome, so ill drop some notes there and we can use that as the issue to track/schedule for implementation when appropriate
