### ISSUE TITLE
How to deploy Data Flow to Cloud Foundry with root certificate

### ISSUE THREAD

**Issue by robdickens** [spring-cloud/spring-cloud-dataflow#3423]
Hi,

I'm trying to deploy DataFlow to Cloud Foundry and my dataflow tasks DB is an Azure PostgreSQL database which is SSL enabled (sounds like a good idea).

When I cf push the Data Flow manifest, i get the following error: 

`Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: Could not open SSL root certificate file /home/vcap/.postgresql/root.crt.
`

Does anyone know how I can supply the root.crt to DataFlow?

Thanks.

**Comment by sabbyanandan** [comment]
Hi, @robdickens. Since you haven't shared the JDBC URL, I'll assume you have the right SSL properties included in the URL to connect against an SSL-enabled Azure Postgres. You can verify the applicable properties from the [Postgres JDBC](https://jdbc.postgresql.org/documentation/head/connect.html) documentation.

The next, of course, is the location of the cert file itself. I can think of 2 options.

1) You could generate the Keystore and Truststore, and have it included in the locally built SCDF server [I bumped into an [example for MySQL](https://www.techrunnr.com/connect-mysql-server-from-spring-boot-application-with-ssl/)]. Upon pushing SCDF to PCF, your JDBC URL would point to the generated files from the configured location, and a successful SSL handshake should go through then.

2) You could add the custom trusted certs in PCF's OpsManager, so every container will automatically receive the cert when the (SCDF) application is deployed [more details [here](https://docs.pivotal.io/pivotalcf/2-6/devguide/deploy-apps/trusted-system-certificates.html)]. Once again, with the JDBC URL configured correctly pointing to the cert file, you should see a successful SSL handshake.

I hope this helps.

Lastly, please ask questions like this in StackOverflow or in Gitter going forward.

**Comment by robdickens** [comment]
@sabbyanandan this isn't a PCF distribution, I've deployed data flow to OSS Cloud Foundry and was looking for specific help in pushing data flow to open source cloud foundry and how to include trusted certificate for postgresql as your deployment instructions under cloud foundry don't list this.

Is this still a stackoverflow question as I assumed this is a step missing from your installation instructions and you'd would want to know?

Happy to raise it elsewhere if you believe this doesn't apply to your cloud foundry installation guide.

**Comment by sabbyanandan** [comment]
Understood. Not sure of the 2nd option from the list as to how it will come together in CF OSS, because there won't be an OpsManager in your environment. Maybe there's a way to add certs via BOSH director; sorry, we are not too familiar in this area. Perhaps you can ask in CF OSS forum in StackOverflow.

However, the 1st suggestion is entirely in your control, though. You can locally build and bundle SCDF with the certs, and then push it to CF with SSL creds in the JDBC URL.

**Comment by robdickens** [comment]
@sabbyanandan thanks for the tip, I will investigate the first one and see how far I get.
