### ISSUE TITLE
Restarting failed job which uses incrementer creates new JobInstance

### ISSUE THREAD

**Issue by trlo-bite** [spring-cloud/spring-cloud-dataflow#3483]
**Description:**
I created a job which uses RunIdIncrementer. When launching task it increments id as expected. However if job fails and I try to restart it using UI, id is also incremented, which results in new JobInstance being created. Is this the correct behavior?
I can restart failed JobInstance by manually entering job parameters but is there a way to do it using restart button?

**Release versions:**
Tested on Spring Cloud Data Flow 2.2.1.RELEASE local and kubernetes

**Comment by cppwfs** [comment]
Unfortunately I could not reproduce.  
Can you provide an example batch application in a github repository.
I created a sample batch application with the runIdIncrementer, 
Launched the application and it failed.   One job instance was created as expected.
I corrected the problem in the application.   I then restarted the failed job.   A new job execution was created as expected, but no new job instance record was created as expected.

**Comment by trlo-bite** [comment]
Hi @cppwfs, thanks for helping. I created example application here https://github.com/trlo-bite/scdf-batch-test
After launching task job fails with run.id=1. Then after restarting it completes with run.id=2 and new job instance is created:

![Screenshot (1)](https://user-images.githubusercontent.com/46348566/66991303-7945eb80-f0d0-11e9-8a6d-fe7758eb631d.jpg)

**Comment by trlo-bite** [comment]
Also I can restart job if task was launched with run.id in arguments. Problem happens when run.id is calculated by incrementer.

**Comment by cppwfs** [comment]
@trlo-bite thank you for the example.   That helped me resolve why I could not reproduce.
This is a bug.   
[Issue]
As discussed above when a user has an incrementer as a part of the job definition and they attempt a restart the job, the incrementer is fired automatically by boot's `JobLauncherCommandLineRunner`.   With the incrementer firing each restart we get a new job instance.  This behavior was introduced in Boot 2.1.x and the sample I was using was using boot 2.0.5, so that is why I didn't see it before.  
[Resolution]
When a user requests a restart for a failed job we need to interrogate the Job-Parameters table for the job and find the identifying parameters and apply those to the command line args of the task execution.   This will guarantee that the same Job Instance will be used.

**Comment by cppwfs** [comment]
The fix is located in this branch.   I'm in the middle of updating the tests.   So you can take this Branch and run with it.  https://github.com/cppwfs/spring-cloud-dataflow/tree/SCDF-3483
