### ISSUE TITLE
scdf2 security logout

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3491]
**Problem description:**
As a user, I use  scdf 2.0 on k8s with uaa security  enabled (or keycloak), and I cannot make work "/logout" from session and remove uaa token from it.

**Solution description:**
Now, I can manually remove the session tokens from uaa or configuring param values for token session timeout...
If  I use "logout" from dashboard, token is still alive into uaa
How can i config "/logout" action from scdf configuration?

**Additional context:**
Uaa 4.30
scdf 2.2.0
keycloack 7.0.0

**Comment by sabbyanandan** [comment]
Hi, @eskuai. The OAuth/SSO lifecycle is owned and governed by the backing identity provider, which in your case is UAA. If the token is valid and is long-lived, as long as the SSO session is valid, even with a logout from SCDF, your SSO session will be still live on the backing identity provider. In other words, we don't attempt to go log you out completely from the identity provider. 

We have intentionally decided not to because the user might be using the same provider for many other apps/systems like SCDF, so if we log them out at the mothership, they will lose the login everywhere. 

Besides that, it is not an easy thing to do since the lifecycle hooks would be an identity provider dependent.

Let's see if @ghillert has any other thoughts to share here.

**Comment by ghillert** [comment]
@sabbyanandan There is one issue we should fix in common security: https://github.com/spring-cloud/spring-cloud-common-security-config/issues/34

**Comment by ghillert** [comment]
@eskuai I noticed a regression related to the `/favicon.ico` which causes a "re-authentication" in the browser. That one will be fixed with PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/3503. It turns out that spring-cloud/spring-cloud-common-security-config#34 was not a relevant issue.

With that PR #3502 in place we will redirect users from the UI to

![image](https://user-images.githubusercontent.com/685363/64941164-9782a800-d801-11e9-875a-788f62044811.png)

without causing re-authentication. However, at present there is no option using the logout feature to also log out the user from the UAA itself (as explained by @sabbyanandan). If this is a feature you like to see, though, we might be able to add it as configurable option (So that users could have bother logout behavior depending on their business use-case).

Another edge-case scenario is basic authentication. When using a browser you should not be authentication using basic authentication but always be redirected to the UAA for authentication. Nonetheless, the REST api does support basic authentication to facilitate username/password authentication for the Data Flow Shell. There might be cases (e.g. during development) that you trigger basic authentication against Spring Cloud Data Flow. In that case the credentials are saved until the browser closes. This is a general issues concerning basic authentication (Not a SCDF issue). As I said under normal circumstance you should not hit this issue, but wanted to mention it for completeness.

**Comment by eskuai** [comment]
Hi @ghillert,

As a user, if I click down the "logout" menu option, I could think that the next time to login the system requests me a user and pass, like anothers  login process.

As a user, i shuolud know or should not, that the system is workinng applying an "abstract SSO".
Then,  a use case, it could be:

If the user click down "logout" and config deployment is configured as "no sso", "single uaa", then revoking token and removing it, as result, you get a valid and expected "logout".

About basic authentication, having a uaa server, i will not spend time on it ...

I request about  a simple, useful, logout action ... at this time ... it is better thant nothing ...
