### ISSUE TITLE
Support Oracle database without additional configuration

### ISSUE THREAD

**Issue by gdubya** [spring-cloud/spring-cloud-dataflow#3506]
Oracle JDBC drivers are [now available in Maven Central](https://medium.com/@kuassimensah/oracle-jdbc-drivers-on-maven-central-64fcf724d8b).

This request is to add out-of-the-box support for Oracle, similar to MySQL, Postgres, et al (see https://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/ section 9.2)

**Comment by sabbyanandan** [comment]
Hi, @gdubya. Though the JAR is available in central, we cannot simply embed it in the shipped SCDF/Skipper binaries because we are still entitled to deal with Oracle's licensing. You as a customer to Oracle, you may have a valid license, so you can patch SCDF/Skipper by building the binaries with the driver, and use it per their licensing terms.

We have taken the stance of only including the open-source friendly database drivers.
