### ISSUE TITLE
Add "streams/scale/" API

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3554]
As a continuation of https://github.com/spring-cloud/spring-cloud-deployer/issues/62, we will have a platform-specific implementation of the SPI, which can then be automatically backed by a public-facing RESTful endpoint exposed in SCDF.

We will have to decide whether this API would be chained under the `/streams` API or something more application-specific.

Depends on:
* https://github.com/spring-cloud/spring-cloud-skipper/issues/911
* #3562 

**Acceptance:**
- Include new API under `/streams/scale` 
- The new API is included in the Java DSL and `DataFlowTemplate`
- Include IT tests to validate this via `DockerComposeIT`

**Comment by jvalkeal** [comment]
Before trying to add new rest api's we could simply try to use existing stream update and see if simply updating deployment property `deployer.*.count=2` would suit our needs. This would surely result minimal changes as we wouldn't necessarily need to change anything on a scdf side.

**Comment by tzolov** [comment]
The `update` command changes the functionality of the deployed pipeline. E.g. by update/rollback an app in a pipeline you effectively change the functional behavior of the  running pipeline.  The non-functional operations such as `scale` or  binder `(re)partition` on the other hand are used to improve the performance or take load issues but they do NOT alter the logic of the running pipeline.

IMO it is important to keep this separation and keep the functional (e.g. update) and non-functional (e.g. scale, repartition ...) operations orthogonal to each other.  We should not aim to reuse update in place of scale just because it might feel easy to hack it that way.

**Comment by sabbyanandan** [comment]
@tzolov: Once when we have this API, let's make sure we have the necessary infrastructure to include it in the Java DSL and DataflowTemplate.

**Comment by jvalkeal** [comment]
Btw, this depends on spring-cloud/spring-cloud-skipper#910 which will be on other PR.

**Comment by tzolov** [comment]
The Deployer [scale](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppDeployer.java#L163) method takes as input a [AppScaleRequest](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/app/AppScaleRequest.java) object that conveys the `deploymentId`, `count` and optional `properties` of the app to be scaled.

Find below few suggestions of how  to extend the Data Flow REST API to accommodate the app scale functionality:

1. `Streams Deployments` API
Note: because the app scale operations apply only to already deployed streams it feels more natural to make it part of the existing `/streams/deployments` resource rather than creating a new `/streams/scale` one. 

- Scale a single app in a stream
```
POST /streams/deployments/scale/{streamName}/{appName}/{count}
Content-Type: application/json
BODY: { ... properties ...} // optional
```
imo, this will be the most frequent way to use the scale.  

* Scale multiple apps in a stream (e.g. bulk)
```
POST /streams/deployments/scale/{streamName}
Content-Type: application/json
BODY: 
[ 
  {"appName": "", "count": "", "properties": {...optional...}},
  {"appName": "", "count": "", "properties": {...optional...}},
  ...
]
```
P.S. This cloud be handy for the SCDF UI to implement an experience similar to (or part of) the stream update page.

2. `Runtime API`
Given that the `GET /runtime/apps/` provides an elaborate information about the apps (e.g. deploymentId) and their instance it makes sense to allow scaling vie POST:
```
POST /runtime/apps/{appId}/scale/{count}
Content-Type: application/json
BODY: { ... properties ...} // optional
```
Note: appId is not the app name but the deployment id!
