### ISSUE TITLE
How to set log direction in SCDF

### ISSUE THREAD

**Issue by duyetphamm** [spring-cloud/spring-cloud-dataflow#3686]
How can I configure the log folder of SCDF and their tasks
I have set 
spring.cloud.deployer.local.workingDirectoriesRoot=D:\\Deploy
in application.properties

However, It does not works, the log of task when I launched is written on java.io.tmpdir (C:/..../temp/).

I am using spring-cloud-dataflow-server-core version 2.3.0.RELEASE

**Comment by sabbyanandan** [comment]
@duyetphamm: It is unclear where you're trying to set this env-var and in what  `application.properties` are you listing it. For incomplete reports like this, unfortunately, we will have to make assumptions, so going forward, please describe the environment, versions and include a sample to complete the report.

If I were to guess, you might be adding this property in your custom task application. If you did, of course, that will not work. This is an SCDF property; meaning, it is expected to be used either when deploying the stream or task definition from SCDF.

To say this differently, you can use this property in SCDF as a [global property](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#_common_application_properties), so all task apps get it at launch time. Otherwise, you can selectively use it at the time of [task launches](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#configuration-local-deployer) via `task launch foo --properties "deployer.<your-task-app-name>.local.workingDirectoriesRoot"`.

Lastly, I see a duplicate post in [StackOverflow](https://stackoverflow.com/questions/59244299/how-to-set-log-direction-in-spring-cloud-dataflow) — please use just StackOverflow for questions like this in the future.
