### ISSUE TITLE
Next execution of scheduled task adds arguments from previous task execution

### ISSUE THREAD

**Issue by trlo-bite** [spring-cloud/spring-cloud-dataflow#3694]
**Description:**
If task is scheduled and then launched manually with new argument, next scheduled execution will have the same argument. I discovered this after restarting batch job which creates new task execution with additional incrementable argument. Next time Kubernetes job was created, new task execution had the same argument which resulted in error (job instance already complete with provided parameters).

**Release versions:**
Spring Cloud Data Flow 2.3.0.RELEASE on Kubernetes

**Steps to reproduce:**
1. Create task and schedule it.
2. Launch same task with some arguments.
3. Next time scheduled task execution is created it will have the same arguments.

**Comment by cppwfs** [comment]
Hello @trlo-bite 
The behavior you discussed was introduced in SCDF 2.3 as a part of the Continuous Deployment.  Information about it can be found [here]https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-task-cd .
i.e. if you relaunch a task without specifying updated properties, the properties from the original launch will be used.   
For example if we have a task definition named `mytaskdef` and it's definition is `timestamp`.
I launch `mytaskdef` with the command line arg `--timestamp.format=YYYY`
Now every subsequent launch of `mytaskdef` will have the timestamp in the format of `YYYY` no matter if it launched from Data Flow or via schedule. 
So the solution to your issue is to create a schedule with a task argument that is empty.  
For example in my scenario above I would create a schedule `myschedule` for `mytaskdef` with the argument `--timestamp.format=`.  Now each time `mytaskdef` is launched by this `myschedule` that timestamp will be the default.

**Comment by sabbyanandan** [comment]
Based on the discussion, we will be removing CLI-args from Task's manifest persistence. The CLI-args is currently not used in the recently added CD flow (SCDF v2.3), anyway, so keeping track of it in the task-manifest is unnecessary. 

Once we do that, any new scheduled launches on an existing task-definition can override the CLI-args independently.

**Comment by trlo-bite** [comment]
Thanks for the update. Using empty argument in schedule doesn't work for me because by default argument is not used in task execution. It is only used to restart specific job instance.
For example `date` argument is calculated by job incrementer based on previous job execution parameters. Argument is passed only when restarting job, e.g. `date=20191212`. If I use `date=` in schedule then empty date overrides incremented date and job fails.

**Comment by cppwfs** [comment]
Hello @trlo-bite ,
We had some discussions on this issue yesterday and changed it to a bug.  
A PR has been submitted to resolve the issue.  https://github.com/spring-cloud/spring-cloud-dataflow/pull/3697

**Comment by mackoftrack** [comment]
I don't think this is fixed? We are seeing the same issue on 2.4.0-RELEASE

**Comment by WeekiXu** [comment]
Me too. The same issue on 2.4.0-RELEASE

**Comment by sabbyanandan** [comment]
@mackoftrack / @trlo-bite: Please share your use-case, where you're running them, and how. As well, any other details that would be relevant for us to reason through why this is not working. Without this info, we won't be able to make any progress. 

Depending on your observations and it is related, we can decide whether to reopen this or create a new issue.

**Comment by WeekiXu** [comment]
composed task named task-debug-sync definition `<task-debug || task-debug3>`
**1st execution launched with Arguments:**
```
Arguments:
    version=1
    timestamp=20200221032900
Parameters:
    app.task-debug-sync.task-debug.sleepTime=0
    app.task-debug-sync.task-debug3.sleepTime=2
```
task-debug-sync has Deployment Properties     
`app.composed-task-runner.composed-task-properties: app.task-debug-sync-task-debug.app.task-debug.sleepTime=0, app.task-debug-sync-task-debug3.app.task-debug3.sleepTime=0`

task-debug-sync.task-debug also has Deployment Properties `app.task-debug.sleepTime: 0` 
task-debug-sync.task-debug3 : `app.task-debug3.sleepTime: 0`

**2nd execution launched with Arguments:** 
```
Arguments:
    version=2
    timestamp=20200221033238
Parameters:
    app.task-debug-sync.task-debug3.sleepTime=1
```
task-debug-sync has Deployment Properties     
`app.composed-task-runner.composed-task-properties: app.task-debug-sync-task-debug3.app.task-debug3.sleepTime=1`
task-debug-sync.task-debug also has Deployment Properties `app.task-debug.sleepTime: 0` 
task-debug-sync.task-debug3 : `app.task-debug3.sleepTime: 1`

**3rd execution launched with**
```
Arguments:
    version=3
    timestamp=20200221033528
Parameters: null
```
same with 2nd execution 
task-debug-sync has Deployment Properties     
`app.composed-task-runner.composed-task-properties: app.task-debug-sync-task-debug3.app.task-debug3.sleepTime=1`

task-debug-sync.task-debug also has Deployment Properties `app.task-debug.sleepTime: 0` 
task-debug-sync.task-debug3 : `app.task-debug3.sleepTime: 1`

And the execution results like this:
**1st**
![image](https://user-images.githubusercontent.com/21303064/75002436-69d01800-549f-11ea-9026-7b151bd52eb0.png)
**2nd**
![image](https://user-images.githubusercontent.com/21303064/75002497-95530280-549f-11ea-959e-c6b8647fbea7.png)
**3rd**
![image](https://user-images.githubusercontent.com/21303064/75002784-8c166580-54a0-11ea-8eb3-3ef029d65450.png)
task-debug-sync.task-debug:
![image](https://user-images.githubusercontent.com/21303064/75002788-90db1980-54a0-11ea-9714-9f6a1d5c4f48.png)
task-debug-sync.task-debug3:
![image](https://user-images.githubusercontent.com/21303064/75002794-96d0fa80-54a0-11ea-84e2-55df33c1f857.png)

**Comment by djgeary** [comment]
This looks like its more to do with properties than arguments, it might be another example of the issue I raised here https://github.com/spring-cloud/spring-cloud-dataflow/issues/3773

On a separate issue aren't deployment properties supposed to be ones prefixed with deployer.* ? So why do app.* ones show up under 'deployment properties' in those screen shots.

**Comment by cppwfs** [comment]
Hello All,
Sorry for the delay in the response.
[Issue 1 Arguments being reused in across different executions]
As far as the original issue of arguments being re-used in different executions, I'm not able to reproduce this.  If you can provide a case where this occurs please share it.
[Issue 2: Properties Being Reused across executions]
@WeekiXu Thank you for the excellent writeup with examples.   @djgeary is correct when he said this issue was raised in #3773.   What you are seeing is the expected behavior.   More can be read about it here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-task-cd
[Issue 3: deployment properties]
@djgeary yeah the name `deployment properties` is a bit blurry.  We should just say something like `Task Execution Properties`.    I'll create an issue and see if we can rename it.
