### ISSUE TITLE
Kafka is incorrectly pulled when provisioning SCDF with RabbitMQ

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3700]
As a user, when provisioning SCDF with RabbitMQ using Docker Compose, I notice that Kafka + ZK is also coming along with it. 

```
± docker-compose -f ./docker-compose.yml \                                                                                                                
               -f ./docker-compose-rabbitmq.yml up

Creating network "spring-cloud-dataflow-server_default" with the default driver
Starting dataflow-rabbitmq        ... 
Creating dataflow-mysql    ...
Creating dataflow-kafka-zookeeper ...
Creating dataflow-mysql           ... done
Creating dataflow-kafka-zookeeper ... done
Creating skipper                  ... done
Creating dataflow-kafka           ... done
Creating dataflow-server          ... done
Creating dataflow-app-import      ... done
```

Maybe this is just an echo message, and it is wrongly showing?

**Comment by sabbyanandan** [comment]
Likewise, the Kafka binder properties are unnecessarily populated in all the deployed streaming applications. When using a different database instead of the default, most likely multiple database properties are populated, as well.

**Comment by tzolov** [comment]
@sabbyanandan, 
- Kafka and Zookeepr are not pulled but disabled overriding their Dockerfile entrypoints. You can run `docker ps` to see that there are no such containers. One possible improvement could be to override and rename the `dataflow-kafka` and `dataflow-kafka-zookeepr` container names to `disabling-kafka` and `disabling-zookeeper`. Then console will print something like: `Creating disabling-kafka-zookeeper`?

- As to the binder properties this is known issue and is been working like this since the very first docker-compose setting.  If we need to change it we MUST break the main docker-compose.yml in at least 2 files. That means it will not be possible to have a single self contained docker-compose to setup all services.
