### ISSUE TITLE
Apache Pulsar as optional middleware for enterprise tenancy

### ISSUE THREAD

**Issue by eskuai** [spring-cloud/spring-cloud-dataflow#3721]
**Problem description:**
As a user, I need to get a multitenant model applying scdf model  and I would like to use Apache Pulsar as multitenant middleware to work it

I think that a scdf oriented to "tenants" is a very interesting option

**Solution description:**
I need an enterprise broker like Apache Pulse as a way to related on k8s namespaces, scdf namespaces, multitenant databases and then a mutitenant broker into a multi region AWS vpcs

About databases models, I think that yugadb or Apache Geode could be very interesting as multitenant and distributed databases for scdf)
We are testing YugabyteDb for dual model, traditional relational and nosql options.

Then, creating an event stream, it is related into a "tenant" and we can see that
it is running on a k8s namespace, on a scdf  namespaces with a user/s? related, using a ddbb tenant and broker tenant ..

``different things in different places``

**Description of alternatives:**
From 
``Apache Pulsar — One Cluster for the Entire Enterprise Using Multi Tenancy``
https://medium.com/capital-one-tech/apache-pulsar-one-cluster-for-the-entire-enterprise-using-multi-tenancy-ac0bd925fbdf

I need to get a model in which, on a k8s cluster, with (1-n?) scdf, and 1-n namespaces on it, using a  multitenant database , and a security server (uaa or keycloak, uaa prefer) and a multitenant middleware ... to apply business cases from tenants to de infraestructure model.

(1-n?) k8s cluster <-> (1-n?) scdf --i dont know <-> 1 ddbb <-> 1 middleware <-> 1 security server

**Additional context:**
Add any other context or explanation about the feature request here.
![image](https://user-images.githubusercontent.com/1777753/71622051-979d8c80-2bd3-11ea-9c38-ae98f6f82d7e.png)

Another view for the idea

![image](https://user-images.githubusercontent.com/1777753/71622532-9c177480-2bd6-11ea-83cb-f77f75c97be2.png)

where you read pulsar ... should be "spring data flow server"

Umm, I am concerned about users and role management in scdf ...

**Comment by sabbyanandan** [comment]
Hi, @eskuai. Yahoo! Japan has had a Spring Cloud Stream binder implementation for Apache Pulsar, and they have been using it in production for a few years now. This is something they presented back in 2017 even [see: https://www.slideshare.net/techblogyahoo/spring-cloud-stream-jjugccc-ccca4]. I've been trying to get in touch with them to hopefully convince them to open-source the binder implementation, but I haven't had success yet. Once when we make progress, we will publicly announce it.

Since this is not directly related to SCDF, but rather it is at the level of SCSt binder implementation that we need it, I am going to close this.
