### ISSUE TITLE
Clobs are removed when using vacuumlo with postgres

### ISSUE THREAD

**Issue by Pieter-Beckers** [spring-cloud/spring-cloud-dataflow#3786]
**Description:**
When using the postgres database with spring cloud data flow, orphaned lobs are created when adding stream/task definition. This causes the postgres maintenance script **vacuumlo** to remove them.

**Release versions:**
spring-cloud-dataflow-server-core-2.3.0.RELEASE.jar

**Steps to reproduce:**
1. Launch spring cloud data flow with postgres setup
2. Create a stream definition
3. Run postgres vacuumlo script on the postgres database
4. Try to access the stream: this fails with logs eg:
`Caused by: org.postgresql.util.PSQLException: ERROR: large object 18755 does not exist
`

**Comment by sabbyanandan** [comment]
Hi, @Pieter-Beckers. There are a few uses of `clob` type in the SCDF/Skipper's schema. I don't know what vaccumlo is, and why it would blindly consider database records that are in use. In your case, it appears a deployed stream has a dependency on some of the `clob` entries in the table — oddly, the records are automatically cleaned up.

Not sure what we can do here to control this since it is a Postgres' tooling and is specific to that. Perhaps you may want to review on the DB side of things as to whether or not this is configurable, so you can achieve the desired behavior.

**Comment by Pieter-Beckers** [comment]
Thank you for your response. We disabled the vacuumlo script for now. That seems to be the only thing we could do.
As for why the vacuumlo treats these large objects as orphaned, is still an open question. Maybe it has something to do in the way the clobs are created? Or with the copying from the temp table that was created in the flyway scripts? More research is needed if we want to use the vacuumlo script again.

**Comment by jvalkeal** [comment]
```
docker run --name test-postgres -d -p 5432:5432 -e POSTGRES_PASSWORD=spring -e POSTGRES_USER=spring -e POSTGRES_DB=dataflow postgres:10
```
```
dataflow=# \dl
        Large objects
  ID   | Owner  | Description 
-------+--------+-------------
....
 16917 | spring | 
....
(133 rows)
```
Indeed this is what would happen:
```
$ docker exec -it test-postgres bash
root@4db2879a026f:/# vacuumlo -n -U spring dataflow
Connected to database "dataflow"
Test run: no large objects will be removed!
Checking package_bytes in public.skipper_package_file
Checking state_machine_context in public.state_machine
Would remove 133 large objects from database "dataflow".
```
There seems to be some comments about this same issue when hibernate is used with postgres.

Bit insane that `vacuumlo` works like that as clearly those refs are in use:
```
dataflow=# select definition_name, definition from stream_definitions;
 definition_name | definition 
-----------------+------------
 s0              | 16917
(1 row)

dataflow=# select definition_name, convert_from(lo_get(definition::oid),'utf8') from stream_definitions;
 definition_name | convert_from 
-----------------+--------------
 s0              | time | log
(1 row)
```

**Comment by Akshathhm** [comment]
Similar issue - Postgres Large Object support in BDR

https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5e67f4788e423969577e0ef8

**Comment by Akshathhm** [comment]
Any planned release/fixes for the issue?

**Comment by sabbyanandan** [comment]
@Pieter-Beckers @Akshathhm: Please see @jvalkeal's observations ^^. I am not sure what more we can do here since the Postgres, it's tooling, and their capabilities are assuming ownership and doing something that is outside the scope of Spring or SCDF.

**Comment by nithril** [comment]
Hi all,

@jvalkeal 
> ```
> There seems to be some comments about this same issue when hibernate is used with postgres.
> 
> Bit insane that `vacuumlo` works like that as clearly those refs are in use:
> ```

The column definition is `text` and not `oid` [1], it is a soft reference it explains with vacuumlo is collecting those large objects. 

The column contains in fact not the stream definition but the oid but as text. The issue is IMHO on the spring cloud data flow/hibernate side that should declare that column as `oid` and not `text`. I was not able to find a clear  explanation on google on the issue and how to fix it properly. 

What I did to fix it is to drop the column `definition` and recreate it with the `oid` type. It seems to do the job. 
 

[1]
```
\d stream_definitions
                       Table "public.stream_definitions"
       Column        |          Type          | Collation | Nullable | Default 
---------------------+------------------------+-----------+----------+---------
 definition_name     | character varying(255) |           | not null | 
 definition          | text                   |           |          | 
 description         | character varying(255) |           |          | 
 original_definition | text                   |           |          | 
Indexes:
    "stream_definitions_pkey" PRIMARY KEY, btree (definition_name)
```
