### ISSUE TITLE
Rename `Deployment Properties` on Task Execution Page in the UI

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#3806]
Just responded to an issue where a user was a bit confused when looking at the name `Deployment Properties` on the UI, thinking we should only be showing `deployer` properties.   Maybe we need to rename it to `Task Execution Properties`.   Thoughts?

**Comment by ilayaperumalg** [comment]
Yeah, this is confusing. 

The `Deployment Properties` is something unfamiliar to the task users while `Task Execution` properties could be slightly confused with the actual task execution properties.

Since these are the `deployer` properties, we can probably say something like `Platform` properties given the task is launched/scheduled in the underlying platform and the deployer properties are for the platform.

Also, the name `Parameters` at the task launch page is confusing as well. 

We can probably move this to SCDF UI.

**Comment by cppwfs** [comment]
Great point!!!!  I'll move this over to the SCDF-UI.   
Also we have to keep in mind that this field shows both deployer and app based propereties.
Moved to SCDF-UI .   Refer to : https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1386
