### ISSUE TITLE
Add Helm 3.0 compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#3850]
As a continuation of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3669, we would have to add the Helm 3.0 compatibility for SCDF chart and its dependent components.

Notes:
- The `helm 2to3 convert scdf` doesn't successfully complete, and it fails with the following error(s). This is due to the dependent charts are assumed as fresh creation as opposed to updating an existing resource (in this case, mysql)
```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Deployment, namespace: default, name: scdf-mysql
```
- It is likely also possible to fail for rabbit, Prometheus, and other optional components enabled via feature-toggles
- Depending on how we fix this, we may have to call out the specific instructions in the docs/guides

**Comment by chrisjs** [comment]
per conversation, the above issue was mainly due to upgrade. the proposed approach for this is:

* update docs per spring-io/dataflow.spring.io#220
* update existing chart to add any helm 3 specific things like bumping apiVersion
* test *clean slate* install
* test *clean slate* installation deletion
* stash changes in branch until helm2 is deprecated / our release

anything outside of those, users should refer to the various helm2->helm3 migration guides based on their environment and requirements

**Comment by chrisjs** [comment]
expected changes stashed in https://github.com/chrisjs/charts/tree/helm3_prep for now
