### ISSUE TITLE
Stop task request stops the job but the job status stays as STARTED

### ISSUE THREAD

**Issue by RodrigoLorente** [spring-cloud/spring-cloud-dataflow#3861]
**Description:**
Trying to stop the execution of a job associated to a task by requesting the stop of the task (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-stopping) produces that the job stops its execution but the status stays as STARTED. If at this point you send a request for stopping the job, it stays with status STOPPING and never reaches to STOPPED. So there is no way to restart it in the future.
The behaviour is the same using the Dashboard or the REST API to stop the task.

If the stop request is sent to the job (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-job-executions-stop) instead to the task, it stops without any problem and reaches the STOPPED status, so it can be restarted. 

**Release versions:**
spring-cloud-dataflow-server: 2.4.0.RELEASE
spring-cloud-task: 2.2.2.RELEASE
spring-boot: 2.1.2.RELEASE
spring: 5.1.4.RELEASE
spring-batch: 4.1.1.RELEASE

**Custom apps:**

**Steps to reproduce:**
- Create a Spring Batch job with Spring Boot and Spring Cloud Task (adding @SpringBootApplication and @EnableTask in the main class). It's necessary that the job has a tasklet step with a long enough sleep for allowing to stop it.
- Create an app in SCDF with the job jar:
![image](https://user-images.githubusercontent.com/45937043/78219624-3205b880-74c0-11ea-9c9e-70924971e975.png)
- Create a simple task for the app:
![image](https://user-images.githubusercontent.com/45937043/78219727-6a0cfb80-74c0-11ea-9a70-fe5cc507ae8e.png)
- Launch the task (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-launching)
- Stop the task (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-task-executions-stopping)
- Launch again the task
- Instead of stopping the task, stop the job (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#api-guide-resources-job-executions-stop)
- If you review the execution logs, the job stops its execution in both cases

**Screenshots:**
Where applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/45937043/78220660-37fc9900-74c2-11ea-8a00-51ee440eef69.png)
In this image it can be viewed the different job executions status:
- Job Executions 2 and 5: No action, they were left to finish.
- Job Execution 1: Job stop request.
- Job Execution 4: Task stop request.
- Job Execution 3: Task stop request followed by a Job stop request.

**Additional context:**

**Comment by cppwfs** [comment]
Hello @RodrigoLorente, 
Thank you for reporting this, However since this is not a bug can you ask this question on Stack Overflow and I'll respond there.  
Thanks!

**Comment by RodrigoLorente** [comment]
Hi @cppwfs 
I opened a related question in Stack Overflow (https://stackoverflow.com/questions/60762954/how-to-get-the-execution-id-of-a-restarted-job-in-spring-cloud-data-flow) where this behaviour was asked about and @ilayaperumalg requested me to open the issue.
Why this is not considered as a bug?
Thanks in advance!

**Comment by cppwfs** [comment]
Hello @RodrigoLorente, @ilayaperumalg 

So I think an explanation is in order on the difference between stopping a task and stopping a job.  When stopping a task, SCDF requests the platform to stop the execution of the app (For local that is a sigterm).  And thus the boot application stops, however the batch job is terminated where it is and thus is left in a status of "STARTING" .   
Now why does SCDF still report the status of the job as `STARTING` since it was the one that stopped  the task?  SCDF gets its Job state directly from the batch tables, and since the app was sig-termed the last state the batch app was starting.   You can add an `AfterTask` execution listener to your task to support the proper cleanup if you app is terminating.  More can be read here: https://docs.spring.io/spring-cloud-task/docs/current/reference/#features-task-execution-listener .
To the last question, After stopping the task, and then stopping the job, why does the status of the job 
remain `STOPPED`.   This is because SCDF requests the batch job to stop, however since the batch job
is no longer running the status is left unchanged (i.e. there is no running batch job to take action for the status). 

So in this case you'd rather stop a job and let Spring batch stop appropriately.  When you stop a task (i.e. sigterm) the batch job will be left in an inconsistent state.

**Comment by RodrigoLorente** [comment]
Hello @cppwfs 

The point is your phrase:
> When you stop a task (i.e. sigterm) the batch job will be left in an inconsistent state.
For me, it is hard to considered this as a correct behavior, but I understand the implications of the sigterm.

**Comment by cppwfs** [comment]
I think the key statement is the last one.   You want to stop the job vs. terminating the application.

**Comment by sabbyanandan** [comment]
@cppwfs: It sounds like we have things that work as designed. Do you have any recommendations to further improve or document the behavior more clearly?

**Comment by cppwfs** [comment]
@sabbyanandan This is by design.  Here is our documentation on stopping a task: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-stopping-task-execution

**Comment by sabbyanandan** [comment]
Thanks for the clarification, Glenn.
