### ISSUE TITLE
Doesn't need to manually register composed-task-runner

### ISSUE THREAD

**Issue by johnlinp** [spring-cloud/spring-cloud-dataflow#4096]
**Description:**
The [user guide](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_configuring_the_composed_task_runner) suggests the users to manually register the task application `composed-task-runner`:

> By default, the Composed Task Runner application is not registered with Spring Cloud Data Flow. Consequently, to launch composed tasks, we must first register the Composed Task Runner as an application with Spring Cloud Data Flow...

However, I saw the `composed-task-runner` already registered as a built-in application in the [built-in application list](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_available_applications).

I think we can remove the part that coaches users to register `composed-task-runner`.

**Release versions:**
2.6.0

**Comment by ilayaperumalg** [comment]
Hi @johnlinp, Thanks for pointing this out. Yes, we need to remove it and the composed tasks shouldn't part of the built-in app list as well.

Since the release of 2.6.0, CTR is automatically configured and downloaded at the time of the task launch.

**Comment by ilayaperumalg** [comment]
Upon checking this at the documentation, I realized that the documentation you mentioned above refers to `2.5.3.RELEASE` instead of `2.6.0`. The correct one for 2.6.0 should be [this](https://docs.spring.io/spring-cloud-dataflow/docs/2.6.0/reference/htmlsingle/#_registering_the_composed_task_runner).

Looks like there is some glitch in setting the `current` documentation to `2.6.0`. We'll have this fixed.

Thanks again for reporting this!

**Comment by johnlinp** [comment]
I see. Thanks for the explanation. I'm closing this issue.
