### ISSUE TITLE
PCF disk space issue.Is there a way to tell SCDF not to download artifact if it already exists

### ISSUE THREAD

**Issue by ajitsingh28feb** [spring-cloud/spring-cloud-dataflow#4138]
Deployed application on PCF but facing Disk space issue after few days. The HTTP based artifacts are always downloaded due to the fact that the resources in a specific URL can be replaced with some other resource.
Is there any way to tell SCDF not to download artifact if it already exists

**Comment by sabbyanandan** [comment]
Hi, @ajitsingh28feb. Apologies for the delayed response. You're correct that the HTTP resolved artifacts are _always_ downloaded to the local disk and that would account towards the disk-quota. That's why we recommend the use of Maven artifactory, so the caching mechanism is readily available.

That said, we have added support to optionally clean up downloaded artifacts via a `autoDeleteMavenArtifacts` flag (see: [docs](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#getting-started)). This option is available in SCDF/Skipper for a long time now, though. You will have to set this property in SCDF and as well as Skipper. Perhaps switch to the latest version of SCDF/Skipper, and configure this property in your `manifest.yml` to take advantage of it.
