### ISSUE TITLE
Limit task name length

### ISSUE THREAD

**Issue by siddhantsorann** [spring-cloud/spring-cloud-dataflow#4163]
**Description:**
We are using SCDF v2.4.0 on Kubernetes. If we create a task with the length of name > 52 characters, it gives an error saying "size must be between 0 and 63". From what I could figure out, this error is thrown by Kubernetes. As the task is launched in a pod and 11 characters are appended to the task name to create the pod name, it increase length of pod name to > 63 which matches the error description. This error might be confusing to some.

**Steps to reproduce:**
Run SCDF on K8s and create a task with name > 52 characters and try to launch it.

**Screenshots:**
<img width="1440" alt="Screenshot 2020-09-23 at 12 08 05 AM" src="https://user-images.githubusercontent.com/19900743/93923510-1b367500-fd31-11ea-9ff8-05acd595e207.png">

To fix this maybe we could add a limit to the length of the task name. I could raise a PR for this if that makes sense.

**Comment by sabbyanandan** [comment]
That seems like a legit gap, after all. While we can add the validation to limit the name, it would still be confusing to grok the platform enforced standards (if we continue to show that error message; also, the error message can be improved). Besides that, this change should consider non-K8s deployments, as well.

That said, restricting the length seems like the best option for both the above-discussed concerns, though. It appears to be neutral and is enforced by the product's UX instead of letting the platform concerns leak to the users. 

@mminella: Do you see concerns limiting the length of the task name?

**Comment by mminella** [comment]
@sabbyanandan None at all. My vote would be let's change it so that we can be consistent across the platforms.

**Comment by sabbyanandan** [comment]
Thanks, Micahel. @siddhantsorann: Feel free to start the dialog with a PR; we can work through the requirements as part of it.

**Comment by siddhantsorann** [comment]
Hey @sabbyanandan I have raised a PR for the validation above, maybe we can now start a discussion around it?

**Comment by cppwfs** [comment]
We did some discovery on this topic and found that this issue leads to some new stories to resolve the problem.   Here they are:
* https://github.com/spring-cloud/spring-cloud-dataflow/issues/4189
* https://github.com/spring-cloud/spring-cloud-dataflow/issues/4190
* https://github.com/spring-cloud/spring-cloud-dataflow/issues/4191
* https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1574
* https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1575

So closing this issue as the primary and we can work the ones above.  
Thanks for bringing this to our attention!!!!
