### ISSUE TITLE
management.metrics.tags.application use of ${} values can't be used by some docker containers.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4214]
Scenario:
Data Flow launches a task using an `entry-point` of `exec` (default) with a container created using Spring Boot 2.4's docker plugin.  
The build pack launche parses the `management.metrics.tags.application=${task.name:unknown}-${task.execution.id:unknown}` property as and empty field.  An example can be seen below:
![image.png](https://images.zenhubusercontent.com/5c93c5e09543816d30f633f7/672f8790-fdf4-4890-ad6c-15915bc21002)
Notice the arg that contains just the `:` character (which means its an empty field, no key or value).    

I'm also curious if this occurs on cloud foundry.

**Comment by tzolov** [comment]
This problem is not related to the common metrics tags per se. Later just happen exemplifies an issue with the Spring Boot container image (e.g. buildpacking implementation)!

As an intermediate workaround one can  disable the default `taskResource` and `streamResource` [definitions](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/config/apps/CommonApplicationProperties.java#L67-L68), by setting the following properties on  Data Flow startup: 

`spring.cloud.dataflow.applicationProperties.taskResource=classpath:fake.yml` and `spring.cloud.dataflow.applicationProperties.streamResource=classpath:fake.yml`

or alternatively for yaml: 

```
- SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_TASKRESOURCE=classpath:fake.yml - 
- SPRING_CLOUD_DATAFLOW_APPLICATIONPROPERTIES_STREAMRESOURCE=classpath:fake.yml
```
Disabling those files will NOT affect the GA Tasks and Einstein Apps metrics collection.  It will break only the 3.0 functional app metrics.

**Comment by cppwfs** [comment]
Awaiting response from the Spring Boot Team on this topic.

**Comment by cppwfs** [comment]
The Boot will resolve this issue.  However it will not be complete till after the 2.7 timeline.   It looks like the fix will not be ready till Mid December, so we need to have a release note on this or add a note to a guide....

**Comment by cppwfs** [comment]
I'll add comment to the dataflow.spring.io troubleshooting guide for containers.

**Comment by cppwfs** [comment]
Added workaround in dataflow.spring.io docs in this PR https://github.com/spring-io/dataflow.spring.io/pull/306

**Comment by tzolov** [comment]
Resolved as part of spring-io/dataflow.spring.io#306
