### ISSUE TITLE
SCDF UI - getting error 500 at the UI when trying to open Tasks definition window

### ISSUE THREAD

**Issue by shalomyasap** [spring-cloud/spring-cloud-dataflow#4358]
We are getting error 500 when trying to open the UI at task definitions window. 
This error raise when task attribute value containing a pipe character - " | ". 
The task defines successfully via REST API with all attributes and their values, including quotes, e.g. <SCDF>/tasks/definitions/TASK_NAME  --data-urlencode "definition=--param-name='abcd|efg'"
 
This occurs at versions SCDF 2.6.5, 2.7.0 and 2.7.1.

The error printed to the log is: 
[APP/PROC/WEB/0] OUT org.springframework.cloud.dataflow.core.dsl.ParseException: 151E:(pos 287): task dsl requires a pair of |
   2021-01-31T19:08:29.42+0000 [APP/PROC/WEB/0] OUT collector-task --param.attribute.name='ABCD|EFG'
...
...
...
[RTR/4] OUT uas-dataflow-server<Domain> - [2021-01-31T19:08:29.314114084Z] "GET /tasks/definitions?page=0&size=20&sort=taskName,ASC HTTP/1.1" 500 0 859 "https://uas-dataflow-server.<Domain>/dashboard/"

![SCDF-UI-TaskDefinition-Error-500](https://user-images.githubusercontent.com/42145016/106427102-714dbe80-646f-11eb-9dd9-a6707c64ab1a.png)

Will appreciate for your response.

**Comment by cppwfs** [comment]
Thank you for reporting the issue.
The issue is occuring on the SCDF server side Line 212 of the TaskDefinitionController.  DataFlow is determining if tasks in the resultset belong to a composed task or if they are independent tasks.  To do this it parses the definition for each of the entries.   The parse is failing because the quotes have been removed during the property sanitization stage located here: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/ArgumentSanitizer.java#L145-L146 .   And since the quotes are missing the `|` the parser thinks it is missaligned task definition.   We can use the TaskDefinition list instead of the task definition resource to determine if the entry is composed task.

**Comment by shalomyasap** [comment]
Hi Glenn,

Thank you for your time and analysis. 
So I guess a fix will be consider at R2.7.2? 

Regards,
Shalom

**Comment by shalomyasap** [comment]
Hi Glenn,

Thank you very much for the quick fix. It’s greatly appreciated.
I'll test it once it will be release, I assume release 2.7.2.

Best regards,
Shalom
