### ISSUE TITLE
Support parenthesis in key name when using shell entry point

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4398]
When launching a task app on kubernetes using data flow a user can specify a entrypoint of shell.   This step will then convert all command line args to environment variables.   However in some cases props are may have characters that are not allowed as environment variables.   Specifically the `()` used by spring batch for its run.id ie. `run.id(long)=25`.    
Spring Cloud Data flow needs to provide :
A) Conversion of () to a special character sequence to replace the parenthesis.   Something like `__op__` for `(`  and `__cp__` for close parenthesis.   For example `--run.id(long)=25` would look be converted to `run_id__op__long__cp__=25`.
B) Provide a environment variable DATA_FLOW_COMMAND_LINE_ARGS that contains a list of environment variables that need to be rehydrated back to command line args.
C) In Spring Cloud Data Flow Samples provide a module that would provide users a customized main method, CommandLineRunner or, ApplicationRunner that would convert these properties back to their original state and use them as the command line args.   For example convert `run_id__op__long__cp__=25` back to `--run.id(long)=25`

**Comment by mminella** [comment]
@cppwfs We should not require a custom runner/main method to use SCDF. This goes against rule number 1 for using SCDF.

**Comment by cppwfs** [comment]
I understand.   It seems we need to provide a tool, doc, or, a data flow sample that does this conversion back to parenthesis.

**Comment by mminella** [comment]
That's missing the point. A user should be able to take a plain Spring Boot application and run it via SCDF. If I need a "tool, doc, or, a data flow sample that does this conversion back to parenthesis" that breaks that rule.

**Comment by benas** [comment]
This issue is valid for any application type that can run on SCDF (which could be a non java app, as mentioned in the [docs](https://dataflow.spring.io/docs/concepts/architecture/#application-types)). I see no way to solve this issue in general, because this docker limitation of ignoring command line args in the `shell` form is beyond SCDF capabilities.

However, if we want to fix this issue for the specific Spring Batch/Boot/CloudTask scenario, then step C) above should be done in Spring Cloud Task [here](https://github.com/spring-cloud/spring-cloud-task/blob/master/spring-cloud-task-batch/src/main/java/org/springframework/cloud/task/batch/handler/TaskJobLauncherApplicationRunner.java#L112), something like:

```diff
@Override
public void run(String... args) throws JobExecutionException {
	logger.info("Running default command line with: " + Arrays.asList(args));
++	String dataFlowEnv = System.getenv("DATA_FLOW_COMMAND_LINE_ARGS");
++	// TODO resolve/interpret env variables set by SCDF and pass them as arguments to the boot app
	launchJobFromProperties(StringUtils.splitArrayElementsIntoProperties(args, "="));
	monitorJobExecutions();
}
```

Since Spring Boot based Batch apps **must** be wrapped in SCT apps to benefit from features like job stats, restartability (which is the original use case of this issue), metrics, etc as described in https://github.com/spring-io/dataflow.spring.io/issues/345, it is SCT that is the main entry point in the chain: SCDF -> SCT app -> Spring Boot app -> Spring Batch job. That's why I believe that step C) should be done in SCT.

**Comment by cppwfs** [comment]
I did present that idea during the meeting on Friday, and it was brought up, that we are asking Spring Cloud Task to fix a Data Flow specific problem.   And thus we moved on to other ideas.

**Comment by cppwfs** [comment]
Closing this issue based on recommendations not to use shell entrypoint for batch apps.   More can be read here: https://github.com/spring-io/dataflow.spring.io/pull/353
