### ISSUE TITLE
Custom prefix and sufix to queues and exchanges when using own instance of RabbitMQ as middware message broker

### ISSUE THREAD

**Issue by NangiDev** [spring-cloud/spring-cloud-dataflow#4593]
**Problem description:**
We are trying to self host Dataflow in a Kubernetes cluster. We have our own managed RabbitMQ instance shared among several teams inside a big company.
We want to use this RabbitMQ instance as our middleware broker, but due to policies being applied by the team managing the RabbitMQ we need to add prefix and suffix to our queues and exchanges as we create them.

**Solution description:**
A way to set some environment variables through overriding the yaml-files in /spring-cloud-dataflow/src/kubernetes/* that sets the prefix and suffix on the queues and exchanges. We need a way to set theses different for queues and exchanges.

Example:
RABBITMQ_QUEUE_PREFIX="TEAM1"
RABBITMQ_QUEUE_SUFFIX="IN"
RABBITMQ_EXCHANGE_PREFIX="TEAM1"
RABBITMQ_EXCHANGE_SUFFIX="OUT"

To result in queues and exchanges:
TEAM1.queuename.IN
TEAM1.exchangename.OUT

**Description of alternatives:**
An alternative is for me to try hunt down the problem myself and try to implement it or self host my own RabbitMQ to use as middleware broker.
I do think this is a useful feature though and for a developer who is experienced with working in this repository this might be an relatively easy fix.

**Comment by sabbyanandan** [comment]
@NangiDev: If you need such customization, you would do this at each Stream application level since these are RMQ + Spring Cloud Stream level concerns. Leaking such global overrides in SCDF to address in a SaaS deployment scenario may not be the right approach. SCDF core itself doesn't provide SaaS-ready capabilities out-of-the-box that's why.

If you have a proposal on how you'd design it, please share it, we can brainstorm it together.

**Comment by markpollack** [comment]
While not "multi-tenant" per-se, it would be a somewhat involved feature.  If there are others who feel similar, please reopen, otherwise we are not going to implement this feature at this time.  Thanks for the feedback.
