### ISSUE TITLE
Service account is not getting set

### ISSUE THREAD

**Issue by gurugubelli** [spring-cloud/spring-cloud-dataflow#4619]
Even though environment variable SPRING_CLOUD_SCHEDULER_KUBERNETES_TASK_SERVICE_ACCOUNT_NAME exists used to work in spring cloud dataflow 2.5.x but  stopped working in 2.8.1. Service account getting set default always rather than custom account.

**Comment by ilayaperumalg** [comment]
You can work around this problem by passing the scheduler properties when creating the scheduler for the task in SCDF as follows:

```
scheduler.kubernetes.taskServiceAccountName=<sa-name>
```

**Comment by ilayaperumalg** [comment]
@cppwfs Could you confirm if the changes from https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/457 fixes this issue please?

**Comment by cppwfs** [comment]
Hello @ilayaperumalg This appears to be another issue.    We will need to investigate further.

**Comment by ilayaperumalg** [comment]
Yes, after some investigation I found that the [DeploymentPropertiesResolver](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/main/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java) in the K8s deployer still has the references ([here](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/e2d29194bc871e70fdad7cde001f6e4a4159dbc5/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java#L628) and [here](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/e2d29194bc871e70fdad7cde001f6e4a4159dbc5/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java#L632)) to the deprecated K8s scheduler properties which need to be fixed. 

Also,[ from the scheduler properties deprecation efforts](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/457), the K8s scheduler switched to use the K8s deployer properties instead. Hence, the resolution for the issue reported in here is eventually fixing the support for `taskServiceAccountName` as a K8s deployer property set as platform properties instead of scheduler property.

**Comment by cppwfs** [comment]
@ilayaperumalg thanks for looking into this.   I have also assigned myself to this issue.

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-deployer-kubernetes #467](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/467) via [**ZenHub**](https://www.zenhub.com/)
