### ISSUE TITLE
dataflow server sometimes fails to start on local deployment

### ISSUE THREAD

**Issue by DemianTinkiel** [spring-cloud/spring-cloud-dataflow#4649]
In a local docker-compose deployment using the [dood approach](https://dataflow.spring.io/docs/installation/local/docker/#docker-stream--task-applications), dataflow and skipper fail to start 2 out 5 times i do `docker-compose up ...`. 

Both data flow and skipper components fail to start because they can't reach mysql container. 
Restarting them again succeeds, which means that they tried to connect before mysql was up. the `depends_on` tag in docker is not a reliable way to prevent this.  Using `restart: on-failure` seems to alleviate the issue but is also not very reliable

I see from [this change](https://github.com/spring-cloud/spring-cloud-dataflow/pull/4494/files#diff-a6b09be8315346659c979d441bf625083dc368cf61e9fe52f19cb696658dc635) that there was at some point the use of the wait-for-it script, what is the recommended way to solve this now?

**Comment by jvalkeal** [comment]
Do you see this just with dood is compose unreliable with all compose files? cc @tzolov

**Comment by DemianTinkiel** [comment]
@jvalkeal I see it with DooD + grafana + influxdb.  I haven't tried the other dockerfiles since I need skipper to be able to deploy containers for me

**Comment by tzolov** [comment]
Hi @DemianTinkiel, 
Thank you for raising this issue! As you've figured it out this is a regression that happen during image switch the new boot's build package images model.  
And this problem **affects both DooD as well as the normal compose deployments!**

Because there are no other ways to control the [docker-compose startup order](https://docs.docker.com/compose/startup-order/) but to perform the check in the application code, we will have to override the entrypoint and introduce back the `wait-for-it.sh` as it used to be!

In the mean time you can test by overriding the dataflow [docker-compose/docker-compose-dood.yml#L41-L47](https://github.com/spring-cloud/spring-cloud-dataflow/blob/c3ab60a22e06d6542dae0f2ea4a45de56540a285/src/docker-compose/docker-compose-dood.yml#L41-L47) and skipper [docker-compose-dood.yml#L60-L66](https://github.com/spring-cloud/spring-cloud-dataflow/blob/c3ab60a22e06d6542dae0f2ea4a45de56540a285/src/docker-compose/docker-compose-dood.yml#L60-L66) entry points like this:

```yaml
    entrypoint: >
      bin/sh -c "
         apt-get update && apt-get install --no-install-recommends -y wget &&
         wget --no-check-certificate -P /tmp/ https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz &&
         tar -xvf /tmp/docker-latest.tgz --directory /tmp/ &&
         mv /tmp/docker/docker /usr/local/bin &&
         wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
         chmod a+x /tmp/wait-for-it.sh &&
         /tmp/wait-for-it.sh mysql:3306 -- /cnb/process/web"
```
Please let me know if this solves this problem for you?
