### ISSUE TITLE
Does SCDF support HA deployment?

### ISSUE THREAD

**Issue by devgodman** [spring-cloud/spring-cloud-dataflow#4661]
I would like to setup SCDF on Kubernetes. 
Is it possible to setup SCDF on two active Kubernetes cluster sharing the same database for high availability?
Besides, does SCDF support multiple replicas too?

**Comment by ilayaperumalg** [comment]
> Is it possible to setup SCDF on two active Kubernetes cluster sharing the same database for high availability?

No, this isn't possible with SCDF/Skipper server instances. 

> Besides, does SCDF support multiple replicas too?

No, it doesn't

Here is some context:
SCDF and Skipper server components are designed to get the benefits of underlying platforms. Since both Kubernetes and Cloud Foundry (the production ready platforms these server components can run) provide the fail-over capability, we didn't intend to make both SCDF/Skipper to be running in multiple instances. Though there were a few attempts in the past (for instance: https://github.com/spring-cloud/spring-cloud-skipper/issues/965) to address, we realised the platform (both K8s and CF) provides enough support to get the setup unaffected. Here are some of the reasons:

1) Both the SCDF as well as Skipper servers are the RESTful applications which orchestrate the incoming Stream/Task lifecycle operations along with other orchestration. 
2) Both of these servers are required to be up only to handle the orchestration/monitoring requests. The availability of these servers can be dealt by the platform (for instance: K8s deployment would make sure the SCDF/Skipper server pods availability). 
3) More importantly, the availability of these server components doesn't impact the deployed applications

**Comment by devgodman** [comment]
Hi @ilayaperumalg, 

Though SCDF and Skipper are for orchestration, they still consume resources. According to the current design, it seems that the only option is to scale up SCDF and Skipper instead of horizontally scale out. This design seems not the mainstream. 

According to my experience, high availability of software 100% relying on the platform is quite dangerous. 
SCDF is a very nice product. It will be good if you can consider to allow it to support multiple replicas and multiple clusters for HA.

**Comment by sabbyanandan** [comment]
Hi, @devgodman. A quick primer: SCDF is a lightweight REST controller with a GUI bundled in it as a Spring Boot application. That's all, no cluster, no extra nodes to worry about from HA/FT perspective. You can, of course, scale SCDF to 2 or any number of instances as you desire. 

Now, for applications deployed/launched by SCDF, SCDF delegates to and adapts to the resiliency semantics provided by the platform where the apps/functions run. If they crash, the platform will resurface and have them run reliably.  

If your goal is to provision SCDF in an active-active or active-passive setup, you may want to review the [SCDF on regional clusters recipe](https://dataflow.spring.io/docs/recipes/cloud-providers/gke-regional-clusters/).

For questions like this, please use StackOverflow going forward.
