### ISSUE TITLE
Add --uri property to registration command

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#480]
As a developer, I'd like to add `--uri` property to `module register` command, so I can register custom application URIs with dataflow-server. 

**Acceptance:**
- `--uri` would replace existing `--coordinates` property
- I could register custom application through:
```
dataflow:>module register --uri maven://<group>:<artifactid>:jar:exec:<version> --type <type> --name <appname>

or

dataflow:>module register --uri file://<filelocation>/<app.jar> --type <type> --name <appname>
```

_note: URI registry would eventually support `maven:`, `file:`, `classpath:`, `http:`, `docker:` as options_

**Comment by styjdt** [comment]
Hi,
I've tested the feature of registering custom modules from `file://` uri. Locally this works, but (as somehow expected) on CloudFoundry server this does not work out. When specifying a file location for the module which is on the local harddrive, registering the module works and it is listed in the list of available modules. Creating a stream: no problem. But when the stream should be deployed, it crashes with `UnknownHostException: C` since it tries to locate the file using my (Windows) path on the admin server...

From my point of view I, as a user would expect that:
1. when specifying a file uri during registering a module, that file is picked up and uploaded to the SCDF server (its artifact repository or whatever), so that it can immediately be reused when creating/deploying streams
2. when registering a module (no matter of the source), the module is checked immediately for availability and validity. Currently one can register complete nonsense and be able to list that using `module list` and even create streams out of that. I'd expect that the fail-fast principle applies here.

I don't know if this is not yet implemented or if it is not intended to work at all. Would be nice to get a statement here.

Alexander

**Comment by sabbyanandan** [comment]
Hi, @styjdt: We recently adapted Spring's `Resource` abstraction for custom app registration workflow, so you now have the ability to register app artifacts as `maven`, `docker`, or other variants. This approach provides broader flexibility and extensibility. 

The following would work when you're using the `Local` implementation of dataflow-server.

```
module register --uri file://<PATH-TO-FILE>/<FILE-exec.jar> --type sink --name foo-log
```

That said, not all the `Resource` variants are functional across all the deployment platforms. Specifically, the use of `file://` based URIs wouldn't work in PCF. There are limitations wrt persistent file system in PCF platform itself. You'd instead have to use `maven://` for registering apps in PCF.  With upcoming PCF releases, there'll be support for docker images, too. You'd be then able to use `docker://<image>` as an alternative.

> Currently one can register complete nonsense and be able to list that using module list and even create streams out of that. I'd expect that the fail-fast principle applies here.

Yes, we are aware of it. Thanks for reporting it, too! We will [add validation rules](https://github.com/spring-cloud/spring-cloud-dataflow/issues/491) around this workflow soon. 

If you've other feedback or suggestions, please feel free to open a new issue.
