### ISSUE TITLE
Error occurs if create Task's Schedule using arguments without '='

### ISSUE THREAD

**Issue by LOG-INFO** [spring-cloud/spring-cloud-dataflow#4828]
**Description:**
When I create a schedule for a task, if I use an argument without '=', an error occurs.

ex) `test1 test2=test2`
expected arguement list `["test1", "test2=test2"]`, but failed to create schedule.

If I modify this to `test2=test2 test1`, It just contains `["test2=test2 test1"]` (key: `test2`, value: `test2 test1`)

**Steps to reproduce:**
1. SCDF UI 
2. Create a schedule from `Tasks` tab
3. Fill `Argument` with **non-key-value-argument**
4. Create Schedule

**Screenshots:**
![image](https://user-images.githubusercontent.com/29394651/153918295-df5fc787-5b89-489a-b2b7-6a8df54e4494.png)

**Additional context:**
My Version: 2.8.3-SNAPSHOT

- https://github.com/spring-cloud/spring-cloud-dataflow/issues/4427

**Comment by cppwfs** [comment]
Hello @LOG-INFO 
All contributions are welcome!

**Comment by cppwfs** [comment]
After chatting with the team, introducing arguments that have a `key` but no `value` would be a breaking change.   This can be seen in the tests and in the discussion on the PR submitted.   The recommended strategy is to have a key/value flag.   So instead of having an argument with just a key ie. `--foo`, it could be written as `--foo=true`.

**Comment by LOG-INFO** [comment]
@cppwfs Thank you :) 
I'll try `--foo=anyValue`
