### ISSUE TITLE
local debug for idea

### ISSUE THREAD

**Issue by GavinAlison** [spring-cloud/spring-cloud-dataflow#4840]
how to debug  multi batch with local idea , run with spring cloud data flow ?

dsl: 
batch 1 && batch 2 && batch3 
it is run with idea to run .

**Comment by cppwfs** [comment]
[Debugging Data Flow launching tasks]
"Main Class" : `org.springframework.cloud.dataflow.server.single.DataFlowServerApplication`
"Environment Variables": `spring_datasource_url=<your db url>;spring_datasource_username=<yourusername>;spring_datasource_password=<yourpassword>;spring_datasource_driverClassName=<yourdriver>`

[Degugging Batch Apps]
Since Data Flow launches batch apps in their own JVM they can't be debugged from data flow directly.   So, debug your batch apps independently in your intellij.

**Comment by cppwfs** [comment]
Hope this helps.
