### ISSUE TITLE
Add Back support for mysql 5.7

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#4879]
TBD

**Comment by onobc** [comment]
I was able to get 2.9.x SCDF running against MySQL 5.7 using the Flyway Teams edition. 

Here is what I did: 

#### Current (base case lets prove its broken)
- Start MySQL 5.7
- Start SCDF 2.9.x w/ MariaDB driver pointing to MySQL 5.7
-  **BIG 💥 💥 EXPLOSION - no 🎲 !!**


#### With Flyway Teams 
- Obtain a Flyway Teams trial license
- Change Flyway dependency in _spring-cloud-dataflow-common-flyway_ 
- Set Flyway license in env var
- Start MySQL 5.7
- Start SCDF 2.9.x w/ MariaDB driver pointing to MySQL 5.7
-  **NO explosions - just 💰 profit!!!**

#### Next Steps
Make this work in PRO only. Will do this next week.

**Comment by onobc** [comment]
ℹ️ SB 2.5.12 runs w/ Flyway 7.7.3 but the trial license only works w/ 8.x so I used the 8.0.5 Flyway version. I am sure we could get l license for the 7.7.3 version if need be. 

I will figure out which version we are currently using in 2.9.x.

**Comment by onobc** [comment]
I have this working for MySQL 5.7 + SB 2.6.6 + Flyway Teams. I will get it ready in a PR.

**Comment by onobc** [comment]
**[Implementation Note]**: We may be able to always use the Flyway teams lib and set the "edition" property to community in the non-pro case. This would allow us to not worry about using different libs in PRO/OSS. This would be good because we do not have a Pro Skipper and therefore would have to deploy 2 skipper libs (w/ and w/o teams lib). 

The hope is the "Warning" message about teams goes away when using the "edition=community" setting.

**Comment by onobc** [comment]
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/8ab2b1e97f7cf6cba7cfb3313caf037bb127f908
