### ISSUE TITLE
Executable SCDF jar

### ISSUE THREAD

**Issue by ccanning** [spring-cloud/spring-cloud-dataflow#4941]
**Problem description:**

We need to run scdf local as a service. Shell already has the executable flag set to true in the spring boot maven plugin.

**Solution description:**
In your Maven build, add this to the spring boot maven plugin configuration:

`<executable>true</executable>`

so, it should look similar to this basic version:

```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <executable>true</executable>
    </configuration>
</plugin>
```

**Description of alternatives:**
If using gradle, use:

```
springBoot {
    executable = true
}
```

**Comment by corneil** [comment]
I would suggest we add these options to a local profile.

**Comment by ccanning** [comment]
> I would suggest we add these options to a local profile.

That would completely meet our needs and it’s probably not required in the other deployment models.

**Comment by onobc** [comment]
We ended up reverting this due to the fact that we ran into possible caveat listed [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#deployment.installing) during our CI pipeline as Paketo was unable to extract the jar. I banged on it for a while but realized that this would be a disruptive change and we could run into further issues downstream. 

I apologize for the false start @ccanning . Reach out if you have any issues w/ the workaround listed above.
