### ISSUE TITLE
Feature Request: Add local accounts + authentication

### ISSUE THREAD

**Issue by Risae** [spring-cloud/spring-cloud-dataflow#4981]
Not entirely sure why it was removed, but having basic authentication using local accounts is very useful for proof-of-concepts.

**Comment by markpollack** [comment]
We standardized on OAuth+OIDC since SCDF 2.0.x.  The security configuration was too complex to support both scenarios.  I think people have had success using keycloak.  here is a sample config - https://github.com/ChimbuChinnadurai/spring-cloud-dataflow-keycloak-integration/blob/main/%3E%3D2.3.0/dataflow-server-config.yml
