### ISSUE TITLE
Spring cloud data flow with kubernetes OAuth2 Redirect Error.

### ISSUE THREAD

**Issue by mnetna** [spring-cloud/spring-cloud-dataflow#5146]
We have applied OAuth2(Gitlab) feature in spring cloud data flow.

When i entered 'http://scdf-domain.com/**dashboard**', page was shown Gitlab login page.
and if i log in, page was redirect 'http://scdf-domain.com/**dashboard**'. it was success.

But when i entered 'http://scdf-domain.com/' , page was shown Gitlab login page.
and then page was redirect 'http://scdf-domain.com/**login**'.
it was wrong. I can't see the dashboard screen. i can see only JSON string.

please, help me.

**Comment by klopfdreh** [comment]
I guess this is working as designed, because the dashboard UI needs to somehow communicate with the backend and the root REST API path is by default `/`. A redirection from `/` to `/dashboard` would break the functionality. 

On other words: You always have to enter `http://scdf-domain.com/dashboard` to access the frontend.

**Comment by corneil** [comment]
Hi @mnetna it is as @klopfdreh explained. The root path is a REST API and `/dashboard` is the path to console. Without authentication configured you would see the same results when visiting the same urls as after you successful authentication.
