### ISSUE TITLE
App versions hardcoded

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow#517]
In `META-INF/application.properties` in spring-cloud-dataflow-server-core, 1.0.0.BUILD-SNAPSHOT is used for all versions. Version should be a placeholder and replaced during a build to match build version.

**Comment by markfisher** [comment]
2 comments:

1) we are going to be moving this file out of "core" so that each server provides its own (in some cases even the resource type, as provided by the URI scheme, will vary)

2) we should not assume that all apps in the properties file will always by in sync with regard to the version

That said, I think enabling placeholder replacement for Maven properties in the build process would be fine... but will need to be configured as such within each dataflow server.

FWIW, in the long run, I am still of the opinion that any dataflow-server (except possibly "local") should start with a clean slate, and that we instead focus on making it simple to register *libraries* of apps (e.g. the "analytics" library, or the "hadoop" library).
