### ISSUE TITLE
SCDF running locally fails to deploy apps

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5232]
Running into an issue when running `2.10.1 locally SCDF+Skipper+H2`. Repro steps are below. We may have an issue w/ the OOTB 2.10.1 running locally like this.

### Summary
Attempt to resolve the 3.2.1 apps is failing on the default repo.spring.io/snapshot maven setting (it used to work because everything was available from there)

#### Summary on maven repos
https://repo.spring.io/snapshot does not work
https://repo.spring.io/libs-snapshot works (for me)
https://repo.spring.io/release works 

#### Steps repro
- wget https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dataflow-server/2.10.1/spring-cloud-dataflow-server-2.10.1.jar
- wget https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-skipper-server/2.9.1/spring-cloud-skipper-server-2.9.1.jar
- delete the org/springframework/cloud/stream/apps from your .m2 repo
- java -jar spring-cloud-dataflow-server-2.10.1.jar
- java -jar spring-cloud-skipper-server-2.9.1.jar

##### Steps In UI
- Navigate to localhost:9393/dashboard
- Add apps -> kafka maven
- Navigate to apps -> click aggregator
- ----> :bomb: - no properties for app in UI and log complains about not able to get resource from /snapshot

**Ok lets try to fix w/…**

- Create democonfig.yml:
  ```
  maven:
    remoteRepositories:
      springRepo:
        url: https://repo.spring.io/release
  ```
- Restart SCDF w/ above file:
  ```
  java -jar spring-cloud-dataflow-server-2.10.1.jar -Dspring.config.additonal-location="/Users/cbono/scdf-run-local/democonfig.yml"
  ```
- Go through “Steps in UI”  above - app props will show up.
- Now do these steps as well:

##### Steps in UI

- Create stream “time | log”
- Deploy stream
- -----> :bomb: - skipper should fail on the snapshot repo as SCDF initially did.

Restart it w/ the same yml from above: 
```
java -jar spring-cloud-skipper-server-2.9.1.jar -Dspring.config.additonal-location="/Users/cbono/scdf-run-local/democonfig.yml"
```

Redo above steps - should deploy fine.

**Comment by corneil** [comment]
Not sure why `-Dspring.config.additional-location` isn't working.

The following did work:
`java -jar spring-cloud-dataflow-server-2.10.1.jar --maven.remote-repositories.springRepo.url=https://repo.spring.io/libs-snapshot`

**Comment by corneil** [comment]
If I create a properties file named application-maven.properties with the following content:

```
maven.remote-repositories.springLibs.url=https://repo.spring.io/libs-snapshot
maven.remote-repositories.central.url=https://repo.maven.apache.org/maven2
```
And use:
`java -jar spring-cloud-dataflow-server-2.10.1.jar --spring.config.additonal-location=/home/pcorneil/work/scdf-local --spring.profiles.active=maven`
then the application works as expected. I can remove the .central property as well since some if the applications like `timestamp-batch-task` isn't available in Maven Central.
The default for in 2.10.2-SNAPSHOT has been changed to `https://repo.spring.io/libs-snapshot` which should resolve this for the future.
I suggest we update the documentation to use `--maven.remote-repositories.springRepo.url=https://repo.spring.io/libs-snapshot`

**Comment by corneil** [comment]
Please note the change to make libs-snapshot the default will be in the next release `2.10.2` which should be out soon.
