### ISSUE TITLE
After Applying oauth2.0, I cannot open dashboard web

### ISSUE THREAD

**Issue by Kim-menu** [spring-cloud/spring-cloud-dataflow#5314]
**Description:**
I applied oauth2.0 to my spring cloud data flow server on k8s.
I used oauth app provided by Github.
all things work well, except the thing that I'll explain below
I cannot see resources that start with '/dashboard'.
After authorized by github oauth2.0, if I access dashboard, the web loading forever.

with chrome developer network tab like this...
![스크린샷 2023-04-24 오전 10 38 34](https://user-images.githubusercontent.com/86512031/233880675-bb9e8504-b468-4a89-9e53-c09ace661367.png)

I append my application.yaml for data flow server.
application.yaml
```
spring:  
	cloud:  
		dataflow:  
			task:  
				platform:  
					kubernetes:  
						accounts:  
							default:  
								limits:  
									memory: 1024Mi  
			security:  
				authorization:  
					provider-role-mappings:  
						github:  
							map-oauth-scopes: true  
							role-mappings:  
								ROLE_CREATE: admin  
								ROLE_DEPLOY: admin  
								ROLE_DESTROY: admin  
								ROLE_MANAGE: admin  
								ROLE_MODIFY: admin  
								ROLE_SCHEDULE: admin  
								ROLE_VIEW: admin  
	security:  
		oauth2:  
			client:  
				registration:  
					github:  
						client-id: ...  
						client-secret: ...  
						redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'  
						authorization-grant-type: authorization_code  
						scope:  
						- admin  
				provider:  
					github:  
						authorization-uri: https://github.com/login/oauth/authorize  
						token-uri: https://github.com/login/oauth/access_token  
						user-info-uri: https://api.github.com/user  
						user-name-attribute: login
```

**Release versions:**
2.10.2

anyone knows solution? 🥲

**Comment by seonwoo960000** [comment]
I'm not sure this is the same case as I experienced, but I had similar problem after applying https and github oauth2. I couldn't excess the dashboard and the chrome kept redirected me to previous dashboard url e.g. `http://xxx.com/dashboard`
My solution was 
1. Go to `chrome://net-internals/#hsts`
2. Add your domain (without protocol such as http or https) 
![image](https://user-images.githubusercontent.com/69591622/234295628-651ec7cf-9542-4cf6-9759-d58744524e42.png)

Hope this might help solve your problem.

**Comment by Kim-menu** [comment]
@seonwoo960000 
I didn't apply ssl(https), so hsts option doesn't work for me 🥲.

Thanks for your kindness

**Comment by Kim-menu** [comment]
I finally have known my stupid behavior.

I run SCDF server on k8s for replica count 2. (I'll say each node as node0, node1)
and there is LB in front of nodes.

so, If i authorize, when I connect with node0, I cannot access resource from node1.

As you can see [here](https://github.com/spring-cloud/spring-cloud-dataflow/issues/5314#issue-1680305502),
some resource redirect me to login page...

I can resolve this problem with fix replica count 1 from 2.

You should choose onle one of 
1. server replica set for HA 
2. auth.

🥲

**Comment by seonwoo960000** [comment]
I think this is not the problem of spring-cloud-dataflow. This seems to happen when we have multiple servers with oauth authentication and have a load balancer that works in round-robin fashion. There is a possibility of infinite loop where there are 2 servers behind round-robin load balancer. You can check out how infinite loop can occur in this [link](https://stackoverflow.com/questions/18836427/how-can-i-make-spring-security-oauth2-work-with-load-balancer#:~:text=The%20second%20thing%20to%20be%20aware%20of%20is%20that%20the%20Spring%20oauth%20implementation%20uses%20sessions%20to%20keep%20track%20of%20where%20the%20user%20is%20an%20the%20authentication%20process.%20If%20you%20aren%27t%20careful%2C%20you%20could%20wind%20up%20in%20an%20%22endless%20loop%22%20scenario.%20Suppose%20you%20have%20two%20oauth%20servers%2D%2DServer%20A%20and%20Server%20B%3A). 

I think there are possible solutions to this problem. 
1. Use sticky session on the load balancer, so that a singel client request reach only one server. 
2. Remove servers from using their own sessions when authenticating.

**Comment by Kim-menu** [comment]
@seonwoo960000 ,
I'm so appreciated by your answer.

actually, the problem that I mention is exactly same with that described in your link.

I also considered sticky-session or spring-session-jdbc, etc.
however, I judge scdf-server on k8s is enough reliable by only one replica.
(because, thanks to k8s restart policy, if server pod go to error state, server will restart soon.
By self experiment, I finally have known scdf server's short dead time doesn't have critical bad effect to task or stream apps.)

Because I don't want to make more operational point on my project, I just decided to be satisfied for reliability of this level.

If I want more reliable later, I can refer your comment. thank you so much!!!!!
