### ISSUE TITLE
Simplify Carvel packages (Part 2)

### ISSUE THREAD

**Issue by onobc** [spring-cloud/spring-cloud-dataflow#5332]
This is a continuation of #5252 

Creating scripts that will make it easy to use Carvel to install/deploy DB and broker and document said scripts.

**Comment by markpollack** [comment]
@cppwfs to review

**Comment by cppwfs** [comment]
Followed the instructions from the reference guide starting here: [11. Deployment using Carvel](https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0-SNAPSHOT/reference/htmlsingle/#configuration-carvel:~:text=10.19.%20Configure%20Scheduling-,11.%20Deployment%20using%20Carvel,-12.%20Required%20Tools)

Target Environment: Minikube

I started minikube with the following script:
```
# Start Fresh remove old instance
minikube stop;
minikube delete;
rm -rf ~/.minikube ~/.kube;

# Start minikube
minikube start --cpus=4 --memory=10240 --driver=docker
```

I distilled the instructions from the documentation to the bash script below
```
#!/bin/bash

pushd ~/project/spring-cloud-dataflow/src/deploy/carvel
eval $(minikube docker-env)

source ./start-deploy.sh rabbitmq scdf oss snapshot
./carvel-use-template.sh
export DOCKER_HUB_USERNAME="*****"
export DOCKER_HUB_PASSWORD="*****"
./prepare-cluster.sh
./setup-scdf-repo.sh
./deploy-local-database.sh postgres
./deploy-local-broker.sh
./deploy-local-prometheus.sh
./deploy-scdf.sh
popd
```

Overall LGTM.  But found the following issues::

- Users must be in the `<base dataflow directory>/src/deploy/carvel` for the scripts to work.   There are yaml files that are required such that if you are not in the carvel directory it will fail.   Instructions need to stipulate this and be updated to remove the `/carvel` portion of the path in the shell commands of the documentation. 
- Need to update the `deploy-scdf.sh` so that if you are deploying on minikube that we skip the ingress step and we create a port forward for the scdf instance.   
- Section Headings in the document need to be set to Level 2 `===` because they are currently at the same level as the [11. Deployment using Carvel](https://docs.spring.io/spring-cloud-dataflow/docs/2.11.0-SNAPSHOT/reference/htmlsingle/#configuration-carvel) section.

**Comment by corneil** [comment]
Update with link to local k8s deployment.

**Comment by corneil** [comment]
@cppwfs The scripts in src/deploy will be packaged in a zip file that will be attached to the Release entry on Github.
