### ISSUE TITLE
Spring Cloud Dataflow getting started http POST fails

### ISSUE THREAD

**Issue by sergiubodiu** [spring-cloud/spring-cloud-dataflow#615]
I'm following the guide http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#getting-started-system-requirements
```
java -jar spring-cloud-dataflow-shell-1.0.0.M2.jar
```
Steps to replicate with redis running

```
1.0.0.M3
Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
dataflow:>stream create --name httptest --definition "http --server.port=9000 | log" --deploy
Created and deployed new stream 'httptest'
dataflow:>http post --target http://localhost:9000 --data "hello world"
> POST (text/plain;Charset=UTF-8) http://localhost:9000 hello world
Failed to access http endpoint http://localhost:9000
```
More troubleshooting
```
$ curl -H "Content-Type: text/plain" localhost:9000 -d 'hello'
curl: (7) Failed to connect to localhost port 9000: Connection refused
$ telnet localhost 9000
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by sabbyanandan** [comment]
Hi, @sergiubodiu:

Apart from Redis, you'd also need Kafka to run SCDF's Local server. We have a [docs PR](https://github.com/spring-cloud/spring-cloud-dataflow/pull/596) with corrections and that will be merged soon. The [quick-start](http://cloud.spring.io/spring-cloud-dataflow/#quick-start) guide includes the right steps that you can use for reference. 

By default we load the application registry with kafka-binder based applications. In your case, it is likely that the applications spawned by SCDF are failing to bootstrap since there's no Kafka to connect. If you tail the `http` application log, you will notice the connection errors.

**Comment by nurgasemetey** [comment]
+1, I am also facing this issue

**Comment by sabbyanandan** [comment]
@nurgasemetey: Could you elaborate on your issue, please? What is your error specifically?

**Comment by sabbyanandan** [comment]
There has been no follow-up discussion on this issue. 

Please try out the latest 1.0.0.RELEASE and the [quick-start](http://cloud.spring.io/spring-cloud-dataflow/#quick-start) guide could help you get started. If you see any other anomaly, feel free to create a separate issue.
