### ISSUE TITLE
Rest: In TaskDeploymentController improvement request parameter naming

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#649]
In `TaskDeploymentController#deploy`:

Rename `properties` to `deploymentProperties`
Rename `params` to `runtimeArguments`

This should make it clearer what the request parameters are used for. Keep in mind that under the hood `runtimeArguments` would translate into `runtimeParams` as part of `DataFlowAppDefinition#createDeploymentRequest`. 

But for Tasks we used the naming of `Arguments` - thus the recommendation to use `runtimeArguments` for the REST API.

**Comment by ghillert** [comment]
Also in `org.springframework.cloud.dataflow.rest.resource.TaskExecutionResource`,

Rename `parameters` to `runtimeArguments`.

Currently it is:

```
	/**
	 * The parameters that were used for this task execution.
	 */
	private List<String> parameters;
```

Should `TaskExecutionResource` also return the `deploymentProperties`?

**Comment by ghillert** [comment]
Further argumentation:

The internal SCDF `DataFlowAppDefinition#createDeploymentRequest` using the property `runtimeParams`. So basically `Task Arguments` == “runtimeParams”. Which begs the question: *Should we label everything `Arguments`-related as `runtimeParams` throughout the code base? And maybe use `Arguments` only as “UI Labels”?*

That way the shell flags `properties` and `params` can stay the same.

**Comment by ghillert** [comment]
The unfortunate situation is that in the UI we use:

![image](https://cloud.githubusercontent.com/assets/685363/15827965/7e96d792-2bdb-11e6-981f-bff52ec4e1e1.png)

**Comment by ghillert** [comment]
Maybe just the UI needs to change?

| Shell       | UI              | REST (Launch) | REST (/tasks/executions) | Backend             |
| ------------|-----------------|---------------|--------------------------|---------------------|
| properties  | Task Parameters | properties    | ??? nothing right now    |deploymentProperties |
| params      | Task Arguments  | params        | parameters               |runtimeParams        |

**Comment by ilayaperumalg** [comment]
That's what I initially thought

**Comment by markpollack** [comment]
That would be the least disruptive change, though honestly 'params' is such a generic term - it is was commandLineArgs, it would be better.

**Comment by markpollack** [comment]
Maybe change REST (/tasks/executions) from parameters to params to be consistent.

**Comment by ghillert** [comment]
So maybe we can define the following acceptance criteria:

| Shell       | UI  *                        | REST (Launch) | REST (/tasks/executions) | Backend             |
| ------------|---------------------------|-----------------|--------------------------|---------------------|
| properties  | *Task Property*      | properties   | ??? nothing right now    |deploymentProperties |
| params      | *Task Parameter*  | params        | *params*               |runtimeParams        |

* Add help text similar to the shell e.g.: `Task Parameter represent the commandline arguments for this launch`

**Comment by mminella** [comment]
Here's what I propose:

| Shell       | UI                        | REST (Launch) | REST (/tasks/executions) | Backend            |
| ------------|---------------------------|-----------------|--------------------------|---------------------|
| `environmentProperties`  | Environment Properties  | `environmentProperties`          | `environmentProperties`   | `AppDeploymentRequest#environmentProperties` |
| `arguments`                      | Task Arguments             | `arguments`        | `arguments`   | `AppDeploymentRequest#commandlineArguments` |
| `properties`                       | Task Properties              | `properties`         | `properties`    |  `AppDefinition#properties` |

I'd also propose the simplification of the UI presented above to only allow arguments to be set at runtime.  Since you can override any boot property from the command line anyways, you get the same impact and the override is stored in the task repository (something I'd think you'd want for auditability).

I realize this option isn't the smallest option presented with regards to effort, but getting the naming right is important as well as the fact that we won't want to change this going forward.

**Comment by cppwfs** [comment]
Just to clarify...  
In the table above it looks like the --properties now refers to boot properties.  If so, does that mean a person can change the properties for the task at runtime.  I thought we agreed the user should not be able to do that, but rather use the arguments.
