### ISSUE TITLE
Inconsistent use of app --name parameter in shell

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#703]
In `app register` name refers to just the name without the type since that has it's own parameter `--type`
For the `app info` command we combine type and name as name, which seems a bit inconsistent

```
app register --type sink --name jdbc --uri docker:springcloudstream/jdbc-sink-kafka:latest
app info --name sink:jdbc
```

**Comment by markfisher** [comment]
I agree this is inconsistent. We should change `app info` IMO.

**Comment by trisberg** [comment]
Maybe make it `id` or have separate parameters for `name` and `type`, or even both ways

```
app info --id sink:jdbc
app info --type sink --name jdbc
```

**Comment by markfisher** [comment]
I'd vote for *only* supporting the distinct `name` and `type` parameters.

**Comment by markfisher** [comment]
after some discussion, we are actually leaning toward having `id` after all since that does provide an option for auto-completion (which due to current non-trivial limitations of the shell would not be possible with `name` and `type` being separate parameters)... we could still add `name` and `type` as an alternative, but at least we would avoid having `name` mean something different for `app info` than it does for `app register`
