### ISSUE TITLE
Restricting to custom app properties

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow#719]
I have built custom app (source module) which has spring-cloud-starter-stream-source-jms as dependency. I have defined spring-configuration-metadata-whitelist.properties so that I could see only my custom app properties. I have following observation - 
1. With module info I see all the properties (they are around 50 or more) which I guess are part of spring boot. I am using spring cloud data flow M3 version
2. From Flo UI I see properties from spring-cloud-starter-stream-source-jms starter app and from custom app. I need to have just my custom app properties visible from flo UI. I was hoping spring-configuration-metadata-whitelist.properties will fix this but still see both starter app and custom app properties. How do I fix this?

Another question in different context
1. If I am using groovy transform OOTB and want to point my custom groovy script in script property provided by groovy module. How do this app would find my groovy script?  guess  I would have to bundled my script in this app so that it finds it on classpath

**Comment by artembilan** [comment]
Re. Groovy Transform Processor. Since it is like:
```
/**
 * Reference to a script used to process messages.
 */
private Resource script;
```
Therefore any Spring Resource implementation can be leveraged. So, your `--groovy-transformer.script=` property can  be as any supported location - `ResourceUtils`: 
```
/** Pseudo URL prefix for loading from the class path: "classpath:" */
public static final String CLASSPATH_URL_PREFIX = "classpath:";

/** URL prefix for loading from the file system: "file:" */
public static final String FILE_URL_PREFIX = "file:";

/** URL prefix for loading from a jar file: "jar:" */
public static final String JAR_URL_PREFIX = "jar:";

/** URL prefix for loading from a war file on Tomcat: "war:" */
public static final String WAR_URL_PREFIX = "war:";

/** URL protocol for a file in the file system: "file" */
public static final String URL_PROTOCOL_FILE = "file";

/** URL protocol for an entry from a jar file: "jar" */
public static final String URL_PROTOCOL_JAR = "jar";

/** URL protocol for an entry from a zip file: "zip" */
public static final String URL_PROTOCOL_ZIP = "zip";

/** URL protocol for an entry from a WebSphere jar file: "wsjar" */
public static final String URL_PROTOCOL_WSJAR = "wsjar";

/** URL protocol for an entry from a JBoss jar file: "vfszip" */
public static final String URL_PROTOCOL_VFSZIP = "vfszip";

/** URL protocol for a JBoss file system resource: "vfsfile" */
public static final String URL_PROTOCOL_VFSFILE = "vfsfile";

/** URL protocol for a general JBoss VFS resource: "vfs" */
public static final String URL_PROTOCOL_VFS = "vfs";
```
M-m-m, plus any valid external URL (`http://`, `ftp://` etc.) which can be resolved to the target resource directly.

Yes, you can bundle script into the customized app, but that isn't so flexible and useful especially if you are going to make it refreshable.

**Comment by sachkk76** [comment]
Thanks @artembilan 
Any inputs on showing up just only custom app properties?

**Comment by sabbyanandan** [comment]
@sachkk76: More details [here](http://docs.spring.io/spring-cloud-dataflow-server-yarn/docs/1.0.0.RC1/reference/htmlsingle/#spring-cloud-dataflow-stream-app-whitelisting).

**Comment by ericbottard** [comment]
There is no way to de-whitelist properties. If they appear in the whitelist in the first place, this is because they were deemed central to the functionality of the starter (and hence any concrete app based on it).

Maybe in you particular case there are too many jms properties in the first place?

One thing we may consider in a future release is "layers" of whitelisting (there are currently two implicit layers, which are discovered e.g. in the shell via successive TAB presses: whitelisted properties and "all properties"). This is not on the table at the moment though.

**Comment by sabbyanandan** [comment]
Hi, @sachkk76: If you're able to get this working, could you please comment and close this issue?

**Comment by sachkk76** [comment]
Yes there a lot of jms properties in place..so now when I created spring-configuration-metadata-whitelist.properties with value as - 
configuration-properties.classes=x.y.z.MyCustomAppSourceProperties
 I could see only my app properties from flo UI. But if you want flo to show only few of them, then as  you mentioned there is not way to de-whilelist it.

**Comment by sachkk76** [comment]
This is working so closing this.
