### ISSUE TITLE
Cloud Foundry Version 1.0.0.M3 not able to authenticate di Bluemix PaaS

### ISSUE THREAD

**Issue by lucaverderame** [spring-cloud/spring-cloud-dataflow#772]
Dear Developers,

for tracking purposes, I recall my  [SO question](http://stackoverflow.com/questions/38162459/spring-cloud-dataflow-on-bluemix-ticktock-example-error) here. I hope that this not cause any trouble.

To summarize, the problem is that Spring Cloud Dataflow for Cloud Foundry is not able to authenticate successfully on Bluemix to deploy streams.

My only successful attempt has been achieved with version 1.0.0.M1 since it exposes the following environment variables `SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI`,
`SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI` 
that in case of Bluemix are respectively: 
`https://login.eu-gb.bluemix.net/UAALoginServerWAR/oauth/token` ,
`https://login.eu-gb.bluemix.net/UAALoginServerWAR/oauth/authorize`

As far as I know, later versions do not allow to specify that. The result is that, trying to reproduce the ticktock example, I got:
```
ERROR 29 --- [io-61588-exec-5] o.s.c.d.s.c.CloudFoundryAppDeployer      : Error creating app luketicktock-log
org.springframework.security.oauth2.client.resource.OAuth2AccessDeniedException: Error requesting access token.
```

Many thanks for your support.

Luca

**Comment by sabbyanandan** [comment]
Hi @lucaverderame: 1.0.0.M1 was released in September 2015 and it is very much outdated. A lot of constructs including the way how you'd interact with OAUTH in Cloud Foundry has changed, too. We would highly recommend upgrading to the latest release. 

That said, please refer to the [security](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.0.0.M3/reference/htmlsingle/#_security) section in the 1.0.0.M3 reference guide. You can either directly [uncomment and update](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.0.0.M3/reference/htmlsingle/#_security) the relevant entries in `dataflow-server.yml` or pass them via `cf set-env` or `SPRING_APPLICATION_JSON` environment variables. 

If you have bugs to report  or feature requests, please open issues in SCDF's [CF-server repo](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry). Lastly, If you're already engaged in SO thread, please use that forum instead of cross-posting the same question.

**Comment by lucaverderame** [comment]
Hi Sabby, many thanks for your response I will definitely investigate and post my results on SO. Sorry again four double posting.
