### ISSUE TITLE
Epic: Add Spring 5.x and Boot 2.x  compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#914]
Build SCDF foundation to be on Spring Framework 5.x and Spring Boot 2.x. 

This epic is the baseline for all the things related to the upgrade and all the child stories are tracked via `boot-2.x-upgrade` label.

Primary focus areas for acceptance tests:
- Skipper
- Scheduler
- Stream
- Task
- Deployer
- Apps
- Samples
- Java DSL / DataflowTemplate / REST-APIs / Shell

**Comment by markpollack** [comment]
I don't think we need a separate branch now, we should instead have the master branch support building against different versions of spring framework and boot.

**Comment by gregturn** [comment]
If you have separate profiles (like Spring Data) you can easily build all profiles to verify backward compatibility.

**Comment by trisberg** [comment]
Should this be for milestone 2.1.0.M1 now?

**Comment by tjormola** [comment]
@sabbyanandan I wonder what these milestone updates indicate. I mean I wonder if there's a known plan to upgrade the SCDF stack to Spring 5/Spring Boot 2.0 based runtime? I'm starting a fresh project where using SCDF would make a lot of sense but I'd like to start with Spring Boot 2.0 generation from the start all the way.

**Comment by sabbyanandan** [comment]
Hi, @tjormola. Spring Cloud Data Flow doesn't leverage any of the upstream Boot/Cloud 2.0 features directly. The core of the 2.0 compatibility is at [Spring Cloud Stream](https://github.com/spring-cloud/spring-cloud-stream/milestones) and [Spring Cloud Task](https://github.com/spring-cloud/spring-cloud-task/milestones), and they are both in the process of graduating to 2.0 GA. Building upon these releases, the stream-apps and task-apps will upgrade to 2.0 respectively.

That said, the 1.3+ line of SCDF should be able to orchestrate 2.0 based SCSt/SCT apps - see spring-cloud/spring-cloud-dataflow#1585.

**Comment by tjormola** [comment]
Oh, I missed this issue, thanks. I suppose it covers my main concern that the SCDF wouldn't able to orchestrate apps based on the 2.0 track due to incompatible changes in the management/actuator interface and certain configuration property names for instance. So I will base my custom apps on 2.0 track and try to manage the flows with Spring Boot 1.5 based SCDF and Skipper, then. Hopefully eventually you get to upgrade the runtime of these services too so you could run your infra services and services implementing custom business logic using the same stack everywhere, i.e. everything would be tracking the same modern release train BOMs.

**Comment by jvalkeal** [comment]
This is now master epic and I'm keeping work in my `gh-914-work*` branches until we're ready to thing about merge.
