### ISSUE TITLE
"Details" button in "Apps" tab of dashboard is kind of underwhelming

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-dataflow#918]
There's no description of the app, only a list of properties (which could be useful I know). I'd expect at least a sentence if not a complete README. Maybe a link to the app source code in github? It's also really slow.

N.B. The property names are capitalized by the browser which is probably not helpful.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#127

**Comment by sabbyanandan** [comment]
This needs to be supported in the core and then UI/Flo automatically adapts to it. Reopening.

Generally, it is slow the first time because we have to resolve and download the application artifact and thereafter, we list the application metadata from the maven cache. We are also thinking about caching just the application metadata [spring-cloud/spring-cloud-deployer#115] and not the entire uber-jar artifact.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/6ca5bc9fac8bbf2f563aac6bc20a0e33c33523fe.
